//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.269
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Vancl.TMS.BLL.AgingMonitoringService {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="DistributionOperateLog", Namespace="http://schemas.datacontract.org/2004/07/RFD.LMS.Model")]
    [System.SerializableAttribute()]
    public partial class DistributionOperateLog : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string AreaField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string CityField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string CurrentDistributionCodeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string DistributionCodeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int MerchantIdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int OperateStationField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.DateTime OperateTimeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int OperateUserField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ProvinceField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ReceiveAreaIdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ReceiveCityIdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ReceiveProvinceIdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string StatusField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<int> TransPortStationIdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<int> TransPortTypeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private long WaybillNoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string WaybillTypeField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Area {
            get {
                return this.AreaField;
            }
            set {
                if ((object.ReferenceEquals(this.AreaField, value) != true)) {
                    this.AreaField = value;
                    this.RaisePropertyChanged("Area");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string City {
            get {
                return this.CityField;
            }
            set {
                if ((object.ReferenceEquals(this.CityField, value) != true)) {
                    this.CityField = value;
                    this.RaisePropertyChanged("City");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string CurrentDistributionCode {
            get {
                return this.CurrentDistributionCodeField;
            }
            set {
                if ((object.ReferenceEquals(this.CurrentDistributionCodeField, value) != true)) {
                    this.CurrentDistributionCodeField = value;
                    this.RaisePropertyChanged("CurrentDistributionCode");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string DistributionCode {
            get {
                return this.DistributionCodeField;
            }
            set {
                if ((object.ReferenceEquals(this.DistributionCodeField, value) != true)) {
                    this.DistributionCodeField = value;
                    this.RaisePropertyChanged("DistributionCode");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int MerchantId {
            get {
                return this.MerchantIdField;
            }
            set {
                if ((this.MerchantIdField.Equals(value) != true)) {
                    this.MerchantIdField = value;
                    this.RaisePropertyChanged("MerchantId");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int OperateStation {
            get {
                return this.OperateStationField;
            }
            set {
                if ((this.OperateStationField.Equals(value) != true)) {
                    this.OperateStationField = value;
                    this.RaisePropertyChanged("OperateStation");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime OperateTime {
            get {
                return this.OperateTimeField;
            }
            set {
                if ((this.OperateTimeField.Equals(value) != true)) {
                    this.OperateTimeField = value;
                    this.RaisePropertyChanged("OperateTime");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int OperateUser {
            get {
                return this.OperateUserField;
            }
            set {
                if ((this.OperateUserField.Equals(value) != true)) {
                    this.OperateUserField = value;
                    this.RaisePropertyChanged("OperateUser");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Province {
            get {
                return this.ProvinceField;
            }
            set {
                if ((object.ReferenceEquals(this.ProvinceField, value) != true)) {
                    this.ProvinceField = value;
                    this.RaisePropertyChanged("Province");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ReceiveAreaId {
            get {
                return this.ReceiveAreaIdField;
            }
            set {
                if ((object.ReferenceEquals(this.ReceiveAreaIdField, value) != true)) {
                    this.ReceiveAreaIdField = value;
                    this.RaisePropertyChanged("ReceiveAreaId");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ReceiveCityId {
            get {
                return this.ReceiveCityIdField;
            }
            set {
                if ((object.ReferenceEquals(this.ReceiveCityIdField, value) != true)) {
                    this.ReceiveCityIdField = value;
                    this.RaisePropertyChanged("ReceiveCityId");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ReceiveProvinceId {
            get {
                return this.ReceiveProvinceIdField;
            }
            set {
                if ((object.ReferenceEquals(this.ReceiveProvinceIdField, value) != true)) {
                    this.ReceiveProvinceIdField = value;
                    this.RaisePropertyChanged("ReceiveProvinceId");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Status {
            get {
                return this.StatusField;
            }
            set {
                if ((object.ReferenceEquals(this.StatusField, value) != true)) {
                    this.StatusField = value;
                    this.RaisePropertyChanged("Status");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<int> TransPortStationId {
            get {
                return this.TransPortStationIdField;
            }
            set {
                if ((this.TransPortStationIdField.Equals(value) != true)) {
                    this.TransPortStationIdField = value;
                    this.RaisePropertyChanged("TransPortStationId");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<int> TransPortType {
            get {
                return this.TransPortTypeField;
            }
            set {
                if ((this.TransPortTypeField.Equals(value) != true)) {
                    this.TransPortTypeField = value;
                    this.RaisePropertyChanged("TransPortType");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public long WaybillNo {
            get {
                return this.WaybillNoField;
            }
            set {
                if ((this.WaybillNoField.Equals(value) != true)) {
                    this.WaybillNoField = value;
                    this.RaisePropertyChanged("WaybillNo");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string WaybillType {
            get {
                return this.WaybillTypeField;
            }
            set {
                if ((object.ReferenceEquals(this.WaybillTypeField, value) != true)) {
                    this.WaybillTypeField = value;
                    this.RaisePropertyChanged("WaybillType");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="AgingMonitoringService.IDistributionOperateLog")]
    public interface IDistributionOperateLog {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IDistributionOperateLog/AddMonitorLog", ReplyAction="http://tempuri.org/IDistributionOperateLog/AddMonitorLogResponse")]
        bool AddMonitorLog(Vancl.TMS.BLL.AgingMonitoringService.DistributionOperateLog log);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IDistributionOperateLogChannel : Vancl.TMS.BLL.AgingMonitoringService.IDistributionOperateLog, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class DistributionOperateLogClient : System.ServiceModel.ClientBase<Vancl.TMS.BLL.AgingMonitoringService.IDistributionOperateLog>, Vancl.TMS.BLL.AgingMonitoringService.IDistributionOperateLog {
        
        public DistributionOperateLogClient() {
        }
        
        public DistributionOperateLogClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public DistributionOperateLogClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public DistributionOperateLogClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public DistributionOperateLogClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public bool AddMonitorLog(Vancl.TMS.BLL.AgingMonitoringService.DistributionOperateLog log) {
            return base.Channel.AddMonitorLog(log);
        }
    }
}
