//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.17929
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Vancl.TMS.BLL.CustomizeFlow {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="FunCode", Namespace="http://schemas.datacontract.org/2004/07/RFD.PMS.Model.BasicSetting.Flow")]
    public enum FunCode : int {
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        FunOrderImport = 1,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        FunAssignDistribution = 2,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        FunAssignStation = 3,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        FunInBound = 4,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        FunPackingStation = 5,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        FunPackingDeliverCenter = 6,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        FunPackingCompany = 7,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        FunOutBoundStation = 8,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        FunOutBoundDeliverCenter = 9,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        FunOutBoundCompany = 10,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        FunNormalIntoStation = 11,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        FunBackOrderIntoStation = 12,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        FunAssignDeliverMan = 13,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        FunNormalTurnStation = 14,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        FunTurnDeliverCenter = 15,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        FunBackStationSuccess = 16,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        FunBackStationRefused = 17,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        FunBackStationStranded = 18,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        FunBackOutStation = 19,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        FunBackInBound = 20,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        FunBackOutBound = 21,
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="FlowNodeCheckerModel", Namespace="http://schemas.datacontract.org/2004/07/RFD.PMS.Model.BasicSetting.Flow")]
    [System.SerializableAttribute()]
    public partial class FlowNodeCheckerModel : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string CheckerTypeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string FormulaField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string CheckerType {
            get {
                return this.CheckerTypeField;
            }
            set {
                if ((object.ReferenceEquals(this.CheckerTypeField, value) != true)) {
                    this.CheckerTypeField = value;
                    this.RaisePropertyChanged("CheckerType");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Formula {
            get {
                return this.FormulaField;
            }
            set {
                if ((object.ReferenceEquals(this.FormulaField, value) != true)) {
                    this.FormulaField = value;
                    this.RaisePropertyChanged("Formula");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="CustomizeFlow.ICustomizeFlow")]
    public interface ICustomizeFlow {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICustomizeFlow/GetDistributionFunChecker", ReplyAction="http://tempuri.org/ICustomizeFlow/GetDistributionFunCheckerResponse")]
        System.Collections.Generic.List<Vancl.TMS.BLL.CustomizeFlow.FlowNodeCheckerModel> GetDistributionFunChecker(string distributionCode, Vancl.TMS.BLL.CustomizeFlow.FunCode funCode);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICustomizeFlow/IsExitsFun", ReplyAction="http://tempuri.org/ICustomizeFlow/IsExitsFunResponse")]
        bool IsExitsFun(string distributionCode, Vancl.TMS.BLL.CustomizeFlow.FunCode funCode);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface ICustomizeFlowChannel : Vancl.TMS.BLL.CustomizeFlow.ICustomizeFlow, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class CustomizeFlowClient : System.ServiceModel.ClientBase<Vancl.TMS.BLL.CustomizeFlow.ICustomizeFlow>, Vancl.TMS.BLL.CustomizeFlow.ICustomizeFlow {
        
        public CustomizeFlowClient() {
        }
        
        public CustomizeFlowClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public CustomizeFlowClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public CustomizeFlowClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public CustomizeFlowClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public System.Collections.Generic.List<Vancl.TMS.BLL.CustomizeFlow.FlowNodeCheckerModel> GetDistributionFunChecker(string distributionCode, Vancl.TMS.BLL.CustomizeFlow.FunCode funCode) {
            return base.Channel.GetDistributionFunChecker(distributionCode, funCode);
        }
        
        public bool IsExitsFun(string distributionCode, Vancl.TMS.BLL.CustomizeFlow.FunCode funCode) {
            return base.Channel.IsExitsFun(distributionCode, funCode);
        }
    }
}
