//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.269
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace InfoClient.ServiceReference1 {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="ServiceReference1.ICaching")]
    public interface ICaching {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICaching/Store", ReplyAction="http://tempuri.org/ICaching/StoreResponse")]
        void Store(Vancl.TMS.Util.CacheService.Cache cache);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICaching/Get", ReplyAction="http://tempuri.org/ICaching/GetResponse")]
        Vancl.TMS.Util.CacheService.Cache Get(string name);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICaching/Remove", ReplyAction="http://tempuri.org/ICaching/RemoveResponse")]
        bool Remove(string name);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface ICachingChannel : InfoClient.ServiceReference1.ICaching, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class CachingClient : System.ServiceModel.ClientBase<InfoClient.ServiceReference1.ICaching>, InfoClient.ServiceReference1.ICaching {
        
        public CachingClient() {
        }
        
        public CachingClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public CachingClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public CachingClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public CachingClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public void Store(Vancl.TMS.Util.CacheService.Cache cache) {
            base.Channel.Store(cache);
        }
        
        public Vancl.TMS.Util.CacheService.Cache Get(string name) {
            return base.Channel.Get(name);
        }
        
        public bool Remove(string name) {
            return base.Channel.Remove(name);
        }
    }
}
