//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.17929
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Vancl.TMS.BLL.WaybillTurnService {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="WaybillTurnModel", Namespace="http://schemas.datacontract.org/2004/07/Cloud.DPS.Model.WaybillTurn")]
    [System.SerializableAttribute()]
    public partial class WaybillTurnModel : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int CreateByField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<System.DateTime> CreateTimeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string FromDistributionCodeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int FromExpressCompanyIdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ToDistributionCodeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int ToExpressCompanyIdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private Vancl.TMS.BLL.WaybillTurnService.EnumCommonWaybillTurnType TurnTypeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int UpdateByField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<System.DateTime> UpdateTimeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private long WaybillNoField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int CreateBy {
            get {
                return this.CreateByField;
            }
            set {
                if ((this.CreateByField.Equals(value) != true)) {
                    this.CreateByField = value;
                    this.RaisePropertyChanged("CreateBy");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<System.DateTime> CreateTime {
            get {
                return this.CreateTimeField;
            }
            set {
                if ((this.CreateTimeField.Equals(value) != true)) {
                    this.CreateTimeField = value;
                    this.RaisePropertyChanged("CreateTime");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string FromDistributionCode {
            get {
                return this.FromDistributionCodeField;
            }
            set {
                if ((object.ReferenceEquals(this.FromDistributionCodeField, value) != true)) {
                    this.FromDistributionCodeField = value;
                    this.RaisePropertyChanged("FromDistributionCode");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int FromExpressCompanyId {
            get {
                return this.FromExpressCompanyIdField;
            }
            set {
                if ((this.FromExpressCompanyIdField.Equals(value) != true)) {
                    this.FromExpressCompanyIdField = value;
                    this.RaisePropertyChanged("FromExpressCompanyId");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ToDistributionCode {
            get {
                return this.ToDistributionCodeField;
            }
            set {
                if ((object.ReferenceEquals(this.ToDistributionCodeField, value) != true)) {
                    this.ToDistributionCodeField = value;
                    this.RaisePropertyChanged("ToDistributionCode");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int ToExpressCompanyId {
            get {
                return this.ToExpressCompanyIdField;
            }
            set {
                if ((this.ToExpressCompanyIdField.Equals(value) != true)) {
                    this.ToExpressCompanyIdField = value;
                    this.RaisePropertyChanged("ToExpressCompanyId");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public Vancl.TMS.BLL.WaybillTurnService.EnumCommonWaybillTurnType TurnType {
            get {
                return this.TurnTypeField;
            }
            set {
                if ((this.TurnTypeField.Equals(value) != true)) {
                    this.TurnTypeField = value;
                    this.RaisePropertyChanged("TurnType");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int UpdateBy {
            get {
                return this.UpdateByField;
            }
            set {
                if ((this.UpdateByField.Equals(value) != true)) {
                    this.UpdateByField = value;
                    this.RaisePropertyChanged("UpdateBy");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<System.DateTime> UpdateTime {
            get {
                return this.UpdateTimeField;
            }
            set {
                if ((this.UpdateTimeField.Equals(value) != true)) {
                    this.UpdateTimeField = value;
                    this.RaisePropertyChanged("UpdateTime");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public long WaybillNo {
            get {
                return this.WaybillNoField;
            }
            set {
                if ((this.WaybillNoField.Equals(value) != true)) {
                    this.WaybillNoField = value;
                    this.RaisePropertyChanged("WaybillNo");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="EnumCommon.WaybillTurnType", Namespace="http://schemas.datacontract.org/2004/07/Cloud.DPS.Model")]
    public enum EnumCommonWaybillTurnType : int {
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        NoTurn = 0,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        ToDep = 1,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        ToDistribution = 1,
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="WaybillTurnService.IWaybillTurnService")]
    public interface IWaybillTurnService {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IWaybillTurnService/WaybillTurn", ReplyAction="http://tempuri.org/IWaybillTurnService/WaybillTurnResponse")]
        void WaybillTurn(Vancl.TMS.BLL.WaybillTurnService.WaybillTurnModel model);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IWaybillTurnService/GetWaybillTurn", ReplyAction="http://tempuri.org/IWaybillTurnService/GetWaybillTurnResponse")]
        Vancl.TMS.BLL.WaybillTurnService.WaybillTurnModel GetWaybillTurn(long waybillNo);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IWaybillTurnServiceChannel : Vancl.TMS.BLL.WaybillTurnService.IWaybillTurnService, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class WaybillTurnServiceClient : System.ServiceModel.ClientBase<Vancl.TMS.BLL.WaybillTurnService.IWaybillTurnService>, Vancl.TMS.BLL.WaybillTurnService.IWaybillTurnService {
        
        public WaybillTurnServiceClient() {
        }
        
        public WaybillTurnServiceClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public WaybillTurnServiceClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public WaybillTurnServiceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public WaybillTurnServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public void WaybillTurn(Vancl.TMS.BLL.WaybillTurnService.WaybillTurnModel model) {
            base.Channel.WaybillTurn(model);
        }
        
        public Vancl.TMS.BLL.WaybillTurnService.WaybillTurnModel GetWaybillTurn(long waybillNo) {
            return base.Channel.GetWaybillTurn(waybillNo);
        }
    }
}
