//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.17929
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Vancl.TMS.BLL.OrdersForWdsAssignService {
    using System.Data;
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="OrdersForWdsAssignService.IOrdersForWdsAssign")]
    public interface IOrdersForWdsAssign {
        
        // CODEGEN: 参数“GetWaitAssignDistributionOrdersResult”需要其他方案信息，使用参数模式无法捕获这些信息。特定特性为“System.Xml.Serialization.XmlArrayAttribute”。
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IOrdersForWdsAssign/GetWaitAssignDistributionOrders", ReplyAction="http://tempuri.org/IOrdersForWdsAssign/GetWaitAssignDistributionOrdersResponse")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        Vancl.TMS.BLL.OrdersForWdsAssignService.GetWaitAssignDistributionOrdersResponse GetWaitAssignDistributionOrders(Vancl.TMS.BLL.OrdersForWdsAssignService.GetWaitAssignDistributionOrdersRequest request);
        
        // CODEGEN: 参数“GetWaitAssignStationOrdersResult”需要其他方案信息，使用参数模式无法捕获这些信息。特定特性为“System.Xml.Serialization.XmlArrayAttribute”。
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IOrdersForWdsAssign/GetWaitAssignStationOrders", ReplyAction="http://tempuri.org/IOrdersForWdsAssign/GetWaitAssignStationOrdersResponse")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        Vancl.TMS.BLL.OrdersForWdsAssignService.GetWaitAssignStationOrdersResponse GetWaitAssignStationOrders(Vancl.TMS.BLL.OrdersForWdsAssignService.GetWaitAssignStationOrdersRequest request);
        
        // CODEGEN: 参数“orderNo”需要其他方案信息，使用参数模式无法捕获这些信息。特定特性为“System.Xml.Serialization.XmlElementAttribute”。
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IOrdersForWdsAssign/AssignDistribution", ReplyAction="http://tempuri.org/IOrdersForWdsAssign/AssignDistributionResponse")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        Vancl.TMS.BLL.OrdersForWdsAssignService.AssignDistributionResponse AssignDistribution(Vancl.TMS.BLL.OrdersForWdsAssignService.AssignDistributionRequest request);
        
        // CODEGEN: 参数“orderNo”需要其他方案信息，使用参数模式无法捕获这些信息。特定特性为“System.Xml.Serialization.XmlElementAttribute”。
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IOrdersForWdsAssign/AssignStation", ReplyAction="http://tempuri.org/IOrdersForWdsAssign/AssignStationResponse")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        Vancl.TMS.BLL.OrdersForWdsAssignService.AssignStationResponse AssignStation(Vancl.TMS.BLL.OrdersForWdsAssignService.AssignStationRequest request);
        
        // CODEGEN: 参数“orderNo”需要其他方案信息，使用参数模式无法捕获这些信息。特定特性为“System.Xml.Serialization.XmlElementAttribute”。
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IOrdersForWdsAssign/IsAssignDistribution", ReplyAction="http://tempuri.org/IOrdersForWdsAssign/IsAssignDistributionResponse")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        Vancl.TMS.BLL.OrdersForWdsAssignService.IsAssignDistributionResponse IsAssignDistribution(Vancl.TMS.BLL.OrdersForWdsAssignService.IsAssignDistributionRequest request);
        
        // CODEGEN: 参数“orderNo”需要其他方案信息，使用参数模式无法捕获这些信息。特定特性为“System.Xml.Serialization.XmlElementAttribute”。
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IOrdersForWdsAssign/IsAssignStation", ReplyAction="http://tempuri.org/IOrdersForWdsAssign/IsAssignStationResponse")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        Vancl.TMS.BLL.OrdersForWdsAssignService.IsAssignStationResponse IsAssignStation(Vancl.TMS.BLL.OrdersForWdsAssignService.IsAssignStationRequest request);
        
        // CODEGEN: 参数“GetAssignDistributionOrdersResult”需要其他方案信息，使用参数模式无法捕获这些信息。特定特性为“System.Xml.Serialization.XmlElementAttribute”。
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IOrdersForWdsAssign/GetAssignDistributionOrders", ReplyAction="http://tempuri.org/IOrdersForWdsAssign/GetAssignDistributionOrdersResponse")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        Vancl.TMS.BLL.OrdersForWdsAssignService.GetAssignDistributionOrdersResponse GetAssignDistributionOrders(Vancl.TMS.BLL.OrdersForWdsAssignService.GetAssignDistributionOrdersRequest request);
        
        // CODEGEN: 参数“GetAssignStationOrdersResult”需要其他方案信息，使用参数模式无法捕获这些信息。特定特性为“System.Xml.Serialization.XmlElementAttribute”。
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IOrdersForWdsAssign/GetAssignStationOrders", ReplyAction="http://tempuri.org/IOrdersForWdsAssign/GetAssignStationOrdersResponse")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        Vancl.TMS.BLL.OrdersForWdsAssignService.GetAssignStationOrdersResponse GetAssignStationOrders(Vancl.TMS.BLL.OrdersForWdsAssignService.GetAssignStationOrdersRequest request);
        
        // CODEGEN: 参数“orderNo”需要其他方案信息，使用参数模式无法捕获这些信息。特定特性为“System.Xml.Serialization.XmlElementAttribute”。
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IOrdersForWdsAssign/OutBound", ReplyAction="http://tempuri.org/IOrdersForWdsAssign/OutBoundResponse")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        Vancl.TMS.BLL.OrdersForWdsAssignService.OutBoundResponse OutBound(Vancl.TMS.BLL.OrdersForWdsAssignService.OutBoundRequest request);
        
        // CODEGEN: 参数“orderNo”需要其他方案信息，使用参数模式无法捕获这些信息。特定特性为“System.Xml.Serialization.XmlElementAttribute”。
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IOrdersForWdsAssign/AssignDistributionChange", ReplyAction="http://tempuri.org/IOrdersForWdsAssign/AssignDistributionChangeResponse")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        Vancl.TMS.BLL.OrdersForWdsAssignService.AssignDistributionChangeResponse AssignDistributionChange(Vancl.TMS.BLL.OrdersForWdsAssignService.AssignDistributionChangeRequest request);
        
        // CODEGEN: 参数“orderno”需要其他方案信息，使用参数模式无法捕获这些信息。特定特性为“System.Xml.Serialization.XmlElementAttribute”。
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IOrdersForWdsAssign/IsOutBound", ReplyAction="http://tempuri.org/IOrdersForWdsAssign/IsOutBoundResponse")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        Vancl.TMS.BLL.OrdersForWdsAssignService.IsOutBoundResponse IsOutBound(Vancl.TMS.BLL.OrdersForWdsAssignService.IsOutBoundRequest request);
        
        // CODEGEN: 参数“orderNo”需要其他方案信息，使用参数模式无法捕获这些信息。特定特性为“System.Xml.Serialization.XmlElementAttribute”。
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IOrdersForWdsAssign/AssignFail", ReplyAction="http://tempuri.org/IOrdersForWdsAssign/AssignFailResponse")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        Vancl.TMS.BLL.OrdersForWdsAssignService.AssignFailResponse AssignFail(Vancl.TMS.BLL.OrdersForWdsAssignService.AssignFailRequest request);
        
        // CODEGEN: 参数“GetAssignDistributionResult”需要其他方案信息，使用参数模式无法捕获这些信息。特定特性为“System.Xml.Serialization.XmlElementAttribute”。
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IOrdersForWdsAssign/GetAssignDistribution", ReplyAction="http://tempuri.org/IOrdersForWdsAssign/GetAssignDistributionResponse")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        Vancl.TMS.BLL.OrdersForWdsAssignService.GetAssignDistributionResponse GetAssignDistribution(Vancl.TMS.BLL.OrdersForWdsAssignService.GetAssignDistributionRequest request);
        
        // CODEGEN: 参数“orderNo”需要其他方案信息，使用参数模式无法捕获这些信息。特定特性为“System.Xml.Serialization.XmlElementAttribute”。
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IOrdersForWdsAssign/GetAssignStation", ReplyAction="http://tempuri.org/IOrdersForWdsAssign/GetAssignStationResponse")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        Vancl.TMS.BLL.OrdersForWdsAssignService.GetAssignStationResponse GetAssignStation(Vancl.TMS.BLL.OrdersForWdsAssignService.GetAssignStationRequest request);
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.17929")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://schemas.datacontract.org/2004/07/Cloud.DPS.Model.AssignModel")]
    public partial class AssignInfoForWds : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string addressField;
        
        private string areaField;
        
        private string areaIdField;
        
        private string assignDistributionCodeField;
        
        private decimal backFundField;
        
        private bool backFundFieldSpecified;
        
        private string cityField;
        
        private string currentDistributionCodeField;
        
        private string distributionCodeField;
        
        private int expressCompanyIdField;
        
        private bool expressCompanyIdFieldSpecified;
        
        private string goodsCategoryField;
        
        private string goodsPropertyField;
        
        private bool isCODField;
        
        private bool isCODFieldSpecified;
        
        private bool isPOSField;
        
        private bool isPOSFieldSpecified;
        
        private int merchantIdField;
        
        private bool merchantIdFieldSpecified;
        
        private decimal needFundField;
        
        private bool needFundFieldSpecified;
        
        private string orderNoField;
        
        private int orderTypeField;
        
        private bool orderTypeFieldSpecified;
        
        private string provinceField;
        
        private string replaceTypeField;
        
        private int sendSortCenterIdField;
        
        private bool sendSortCenterIdFieldSpecified;
        
        private int sortingCenterIdField;
        
        private bool sortingCenterIdFieldSpecified;
        
        private string wareHouseIdField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=0)]
        public string Address {
            get {
                return this.addressField;
            }
            set {
                this.addressField = value;
                this.RaisePropertyChanged("Address");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=1)]
        public string Area {
            get {
                return this.areaField;
            }
            set {
                this.areaField = value;
                this.RaisePropertyChanged("Area");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=2)]
        public string AreaId {
            get {
                return this.areaIdField;
            }
            set {
                this.areaIdField = value;
                this.RaisePropertyChanged("AreaId");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=3)]
        public string AssignDistributionCode {
            get {
                return this.assignDistributionCodeField;
            }
            set {
                this.assignDistributionCodeField = value;
                this.RaisePropertyChanged("AssignDistributionCode");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=4)]
        public decimal BackFund {
            get {
                return this.backFundField;
            }
            set {
                this.backFundField = value;
                this.RaisePropertyChanged("BackFund");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool BackFundSpecified {
            get {
                return this.backFundFieldSpecified;
            }
            set {
                this.backFundFieldSpecified = value;
                this.RaisePropertyChanged("BackFundSpecified");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=5)]
        public string City {
            get {
                return this.cityField;
            }
            set {
                this.cityField = value;
                this.RaisePropertyChanged("City");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=6)]
        public string CurrentDistributionCode {
            get {
                return this.currentDistributionCodeField;
            }
            set {
                this.currentDistributionCodeField = value;
                this.RaisePropertyChanged("CurrentDistributionCode");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=7)]
        public string DistributionCode {
            get {
                return this.distributionCodeField;
            }
            set {
                this.distributionCodeField = value;
                this.RaisePropertyChanged("DistributionCode");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=8)]
        public int ExpressCompanyId {
            get {
                return this.expressCompanyIdField;
            }
            set {
                this.expressCompanyIdField = value;
                this.RaisePropertyChanged("ExpressCompanyId");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool ExpressCompanyIdSpecified {
            get {
                return this.expressCompanyIdFieldSpecified;
            }
            set {
                this.expressCompanyIdFieldSpecified = value;
                this.RaisePropertyChanged("ExpressCompanyIdSpecified");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=9)]
        public string GoodsCategory {
            get {
                return this.goodsCategoryField;
            }
            set {
                this.goodsCategoryField = value;
                this.RaisePropertyChanged("GoodsCategory");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=10)]
        public string GoodsProperty {
            get {
                return this.goodsPropertyField;
            }
            set {
                this.goodsPropertyField = value;
                this.RaisePropertyChanged("GoodsProperty");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=11)]
        public bool IsCOD {
            get {
                return this.isCODField;
            }
            set {
                this.isCODField = value;
                this.RaisePropertyChanged("IsCOD");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool IsCODSpecified {
            get {
                return this.isCODFieldSpecified;
            }
            set {
                this.isCODFieldSpecified = value;
                this.RaisePropertyChanged("IsCODSpecified");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=12)]
        public bool IsPOS {
            get {
                return this.isPOSField;
            }
            set {
                this.isPOSField = value;
                this.RaisePropertyChanged("IsPOS");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool IsPOSSpecified {
            get {
                return this.isPOSFieldSpecified;
            }
            set {
                this.isPOSFieldSpecified = value;
                this.RaisePropertyChanged("IsPOSSpecified");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=13)]
        public int MerchantId {
            get {
                return this.merchantIdField;
            }
            set {
                this.merchantIdField = value;
                this.RaisePropertyChanged("MerchantId");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool MerchantIdSpecified {
            get {
                return this.merchantIdFieldSpecified;
            }
            set {
                this.merchantIdFieldSpecified = value;
                this.RaisePropertyChanged("MerchantIdSpecified");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=14)]
        public decimal NeedFund {
            get {
                return this.needFundField;
            }
            set {
                this.needFundField = value;
                this.RaisePropertyChanged("NeedFund");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool NeedFundSpecified {
            get {
                return this.needFundFieldSpecified;
            }
            set {
                this.needFundFieldSpecified = value;
                this.RaisePropertyChanged("NeedFundSpecified");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=15)]
        public string OrderNo {
            get {
                return this.orderNoField;
            }
            set {
                this.orderNoField = value;
                this.RaisePropertyChanged("OrderNo");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=16)]
        public int OrderType {
            get {
                return this.orderTypeField;
            }
            set {
                this.orderTypeField = value;
                this.RaisePropertyChanged("OrderType");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool OrderTypeSpecified {
            get {
                return this.orderTypeFieldSpecified;
            }
            set {
                this.orderTypeFieldSpecified = value;
                this.RaisePropertyChanged("OrderTypeSpecified");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=17)]
        public string Province {
            get {
                return this.provinceField;
            }
            set {
                this.provinceField = value;
                this.RaisePropertyChanged("Province");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=18)]
        public string ReplaceType {
            get {
                return this.replaceTypeField;
            }
            set {
                this.replaceTypeField = value;
                this.RaisePropertyChanged("ReplaceType");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=19)]
        public int SendSortCenterId {
            get {
                return this.sendSortCenterIdField;
            }
            set {
                this.sendSortCenterIdField = value;
                this.RaisePropertyChanged("SendSortCenterId");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool SendSortCenterIdSpecified {
            get {
                return this.sendSortCenterIdFieldSpecified;
            }
            set {
                this.sendSortCenterIdFieldSpecified = value;
                this.RaisePropertyChanged("SendSortCenterIdSpecified");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=20)]
        public int SortingCenterId {
            get {
                return this.sortingCenterIdField;
            }
            set {
                this.sortingCenterIdField = value;
                this.RaisePropertyChanged("SortingCenterId");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool SortingCenterIdSpecified {
            get {
                return this.sortingCenterIdFieldSpecified;
            }
            set {
                this.sortingCenterIdFieldSpecified = value;
                this.RaisePropertyChanged("SortingCenterIdSpecified");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=21)]
        public string WareHouseId {
            get {
                return this.wareHouseIdField;
            }
            set {
                this.wareHouseIdField = value;
                this.RaisePropertyChanged("WareHouseId");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.17929")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://schemas.datacontract.org/2004/07/Cloud.DPS.Model.DTOModel.ForWDS")]
    public partial class SQQueryCondition : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string areaIdField;
        
        private int assignStatusField;
        
        private bool assignStatusFieldSpecified;
        
        private int assignTypeField;
        
        private bool assignTypeFieldSpecified;
        
        private string cityIdField;
        
        private string currentDistributionCodeField;
        
        private string deliverStationField;
        
        private string fromDistributionCodeField;
        
        private int merchantIdField;
        
        private bool merchantIdFieldSpecified;
        
        private int noTypeField;
        
        private bool noTypeFieldSpecified;
        
        private string noValueField;
        
        private string provinceIdField;
        
        private System.Nullable<System.DateTime> startDateField;
        
        private bool startDateFieldSpecified;
        
        private System.Nullable<System.DateTime> stopDateField;
        
        private bool stopDateFieldSpecified;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=0)]
        public string AreaId {
            get {
                return this.areaIdField;
            }
            set {
                this.areaIdField = value;
                this.RaisePropertyChanged("AreaId");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public int AssignStatus {
            get {
                return this.assignStatusField;
            }
            set {
                this.assignStatusField = value;
                this.RaisePropertyChanged("AssignStatus");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool AssignStatusSpecified {
            get {
                return this.assignStatusFieldSpecified;
            }
            set {
                this.assignStatusFieldSpecified = value;
                this.RaisePropertyChanged("AssignStatusSpecified");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public int AssignType {
            get {
                return this.assignTypeField;
            }
            set {
                this.assignTypeField = value;
                this.RaisePropertyChanged("AssignType");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool AssignTypeSpecified {
            get {
                return this.assignTypeFieldSpecified;
            }
            set {
                this.assignTypeFieldSpecified = value;
                this.RaisePropertyChanged("AssignTypeSpecified");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=3)]
        public string CityId {
            get {
                return this.cityIdField;
            }
            set {
                this.cityIdField = value;
                this.RaisePropertyChanged("CityId");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=4)]
        public string CurrentDistributionCode {
            get {
                return this.currentDistributionCodeField;
            }
            set {
                this.currentDistributionCodeField = value;
                this.RaisePropertyChanged("CurrentDistributionCode");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=5)]
        public string DeliverStation {
            get {
                return this.deliverStationField;
            }
            set {
                this.deliverStationField = value;
                this.RaisePropertyChanged("DeliverStation");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=6)]
        public string FromDistributionCode {
            get {
                return this.fromDistributionCodeField;
            }
            set {
                this.fromDistributionCodeField = value;
                this.RaisePropertyChanged("FromDistributionCode");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=7)]
        public int MerchantId {
            get {
                return this.merchantIdField;
            }
            set {
                this.merchantIdField = value;
                this.RaisePropertyChanged("MerchantId");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool MerchantIdSpecified {
            get {
                return this.merchantIdFieldSpecified;
            }
            set {
                this.merchantIdFieldSpecified = value;
                this.RaisePropertyChanged("MerchantIdSpecified");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=8)]
        public int NoType {
            get {
                return this.noTypeField;
            }
            set {
                this.noTypeField = value;
                this.RaisePropertyChanged("NoType");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool NoTypeSpecified {
            get {
                return this.noTypeFieldSpecified;
            }
            set {
                this.noTypeFieldSpecified = value;
                this.RaisePropertyChanged("NoTypeSpecified");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=9)]
        public string NoValue {
            get {
                return this.noValueField;
            }
            set {
                this.noValueField = value;
                this.RaisePropertyChanged("NoValue");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=10)]
        public string ProvinceId {
            get {
                return this.provinceIdField;
            }
            set {
                this.provinceIdField = value;
                this.RaisePropertyChanged("ProvinceId");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=11)]
        public System.Nullable<System.DateTime> StartDate {
            get {
                return this.startDateField;
            }
            set {
                this.startDateField = value;
                this.RaisePropertyChanged("StartDate");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool StartDateSpecified {
            get {
                return this.startDateFieldSpecified;
            }
            set {
                this.startDateFieldSpecified = value;
                this.RaisePropertyChanged("StartDateSpecified");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=12)]
        public System.Nullable<System.DateTime> StopDate {
            get {
                return this.stopDateField;
            }
            set {
                this.stopDateField = value;
                this.RaisePropertyChanged("StopDate");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool StopDateSpecified {
            get {
                return this.stopDateFieldSpecified;
            }
            set {
                this.stopDateFieldSpecified = value;
                this.RaisePropertyChanged("StopDateSpecified");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.17929")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://schemas.datacontract.org/2004/07/Cloud.DPS.Model.DTOModel.ForWDS")]
    public partial class DQQueryCondition : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string areaIdField;
        
        private string assignDistributionCodeField;
        
        private int assignStatusField;
        
        private bool assignStatusFieldSpecified;
        
        private string cityIdField;
        
        private string currentDistributionCodeField;
        
        private string fromDistributionCodeField;
        
        private int merchantIdField;
        
        private bool merchantIdFieldSpecified;
        
        private int noTypeField;
        
        private bool noTypeFieldSpecified;
        
        private string noValueField;
        
        private string provinceIdField;
        
        private System.Nullable<System.DateTime> startDateField;
        
        private bool startDateFieldSpecified;
        
        private int statusField;
        
        private bool statusFieldSpecified;
        
        private System.Nullable<System.DateTime> stopDateField;
        
        private bool stopDateFieldSpecified;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=0)]
        public string AreaId {
            get {
                return this.areaIdField;
            }
            set {
                this.areaIdField = value;
                this.RaisePropertyChanged("AreaId");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=1)]
        public string AssignDistributionCode {
            get {
                return this.assignDistributionCodeField;
            }
            set {
                this.assignDistributionCodeField = value;
                this.RaisePropertyChanged("AssignDistributionCode");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public int AssignStatus {
            get {
                return this.assignStatusField;
            }
            set {
                this.assignStatusField = value;
                this.RaisePropertyChanged("AssignStatus");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool AssignStatusSpecified {
            get {
                return this.assignStatusFieldSpecified;
            }
            set {
                this.assignStatusFieldSpecified = value;
                this.RaisePropertyChanged("AssignStatusSpecified");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=3)]
        public string CityId {
            get {
                return this.cityIdField;
            }
            set {
                this.cityIdField = value;
                this.RaisePropertyChanged("CityId");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=4)]
        public string CurrentDistributionCode {
            get {
                return this.currentDistributionCodeField;
            }
            set {
                this.currentDistributionCodeField = value;
                this.RaisePropertyChanged("CurrentDistributionCode");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=5)]
        public string FromDistributionCode {
            get {
                return this.fromDistributionCodeField;
            }
            set {
                this.fromDistributionCodeField = value;
                this.RaisePropertyChanged("FromDistributionCode");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=6)]
        public int MerchantId {
            get {
                return this.merchantIdField;
            }
            set {
                this.merchantIdField = value;
                this.RaisePropertyChanged("MerchantId");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool MerchantIdSpecified {
            get {
                return this.merchantIdFieldSpecified;
            }
            set {
                this.merchantIdFieldSpecified = value;
                this.RaisePropertyChanged("MerchantIdSpecified");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=7)]
        public int NoType {
            get {
                return this.noTypeField;
            }
            set {
                this.noTypeField = value;
                this.RaisePropertyChanged("NoType");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool NoTypeSpecified {
            get {
                return this.noTypeFieldSpecified;
            }
            set {
                this.noTypeFieldSpecified = value;
                this.RaisePropertyChanged("NoTypeSpecified");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=8)]
        public string NoValue {
            get {
                return this.noValueField;
            }
            set {
                this.noValueField = value;
                this.RaisePropertyChanged("NoValue");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=9)]
        public string ProvinceId {
            get {
                return this.provinceIdField;
            }
            set {
                this.provinceIdField = value;
                this.RaisePropertyChanged("ProvinceId");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=10)]
        public System.Nullable<System.DateTime> StartDate {
            get {
                return this.startDateField;
            }
            set {
                this.startDateField = value;
                this.RaisePropertyChanged("StartDate");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool StartDateSpecified {
            get {
                return this.startDateFieldSpecified;
            }
            set {
                this.startDateFieldSpecified = value;
                this.RaisePropertyChanged("StartDateSpecified");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=11)]
        public int Status {
            get {
                return this.statusField;
            }
            set {
                this.statusField = value;
                this.RaisePropertyChanged("Status");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool StatusSpecified {
            get {
                return this.statusFieldSpecified;
            }
            set {
                this.statusFieldSpecified = value;
                this.RaisePropertyChanged("StatusSpecified");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=12)]
        public System.Nullable<System.DateTime> StopDate {
            get {
                return this.stopDateField;
            }
            set {
                this.stopDateField = value;
                this.RaisePropertyChanged("StopDate");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool StopDateSpecified {
            get {
                return this.stopDateFieldSpecified;
            }
            set {
                this.stopDateFieldSpecified = value;
                this.RaisePropertyChanged("StopDateSpecified");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="GetWaitAssignDistributionOrders", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class GetWaitAssignDistributionOrdersRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        public int assignStatus;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=1)]
        public int top;
        
        public GetWaitAssignDistributionOrdersRequest() {
        }
        
        public GetWaitAssignDistributionOrdersRequest(int assignStatus, int top) {
            this.assignStatus = assignStatus;
            this.top = top;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="GetWaitAssignDistributionOrdersResponse", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class GetWaitAssignDistributionOrdersResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        [System.Xml.Serialization.XmlArrayAttribute(IsNullable=true)]
        [System.Xml.Serialization.XmlArrayItemAttribute(Namespace="http://schemas.datacontract.org/2004/07/Cloud.DPS.Model.AssignModel")]
        public Vancl.TMS.BLL.OrdersForWdsAssignService.AssignInfoForWds[] GetWaitAssignDistributionOrdersResult;
        
        public GetWaitAssignDistributionOrdersResponse() {
        }
        
        public GetWaitAssignDistributionOrdersResponse(Vancl.TMS.BLL.OrdersForWdsAssignService.AssignInfoForWds[] GetWaitAssignDistributionOrdersResult) {
            this.GetWaitAssignDistributionOrdersResult = GetWaitAssignDistributionOrdersResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="GetWaitAssignStationOrders", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class GetWaitAssignStationOrdersRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        public int assignStatus;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=1)]
        public int top;
        
        public GetWaitAssignStationOrdersRequest() {
        }
        
        public GetWaitAssignStationOrdersRequest(int assignStatus, int top) {
            this.assignStatus = assignStatus;
            this.top = top;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="GetWaitAssignStationOrdersResponse", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class GetWaitAssignStationOrdersResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        [System.Xml.Serialization.XmlArrayAttribute(IsNullable=true)]
        [System.Xml.Serialization.XmlArrayItemAttribute(Namespace="http://schemas.datacontract.org/2004/07/Cloud.DPS.Model.AssignModel")]
        public Vancl.TMS.BLL.OrdersForWdsAssignService.AssignInfoForWds[] GetWaitAssignStationOrdersResult;
        
        public GetWaitAssignStationOrdersResponse() {
        }
        
        public GetWaitAssignStationOrdersResponse(Vancl.TMS.BLL.OrdersForWdsAssignService.AssignInfoForWds[] GetWaitAssignStationOrdersResult) {
            this.GetWaitAssignStationOrdersResult = GetWaitAssignStationOrdersResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="AssignDistribution", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class AssignDistributionRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string orderNo;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=1)]
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string fromDistributionCode;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=2)]
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string curDistributionCode;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=3)]
        public int assignType;
        
        public AssignDistributionRequest() {
        }
        
        public AssignDistributionRequest(string orderNo, string fromDistributionCode, string curDistributionCode, int assignType) {
            this.orderNo = orderNo;
            this.fromDistributionCode = fromDistributionCode;
            this.curDistributionCode = curDistributionCode;
            this.assignType = assignType;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="AssignDistributionResponse", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class AssignDistributionResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        public int AssignDistributionResult;
        
        public AssignDistributionResponse() {
        }
        
        public AssignDistributionResponse(int AssignDistributionResult) {
            this.AssignDistributionResult = AssignDistributionResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="AssignStation", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class AssignStationRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string orderNo;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=1)]
        public int stationId;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=2)]
        public int assignType;
        
        public AssignStationRequest() {
        }
        
        public AssignStationRequest(string orderNo, int stationId, int assignType) {
            this.orderNo = orderNo;
            this.stationId = stationId;
            this.assignType = assignType;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="AssignStationResponse", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class AssignStationResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        public int AssignStationResult;
        
        public AssignStationResponse() {
        }
        
        public AssignStationResponse(int AssignStationResult) {
            this.AssignStationResult = AssignStationResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="IsAssignDistribution", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class IsAssignDistributionRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string orderNo;
        
        public IsAssignDistributionRequest() {
        }
        
        public IsAssignDistributionRequest(string orderNo) {
            this.orderNo = orderNo;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="IsAssignDistributionResponse", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class IsAssignDistributionResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        public bool IsAssignDistributionResult;
        
        public IsAssignDistributionResponse() {
        }
        
        public IsAssignDistributionResponse(bool IsAssignDistributionResult) {
            this.IsAssignDistributionResult = IsAssignDistributionResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="IsAssignStation", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class IsAssignStationRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string orderNo;
        
        public IsAssignStationRequest() {
        }
        
        public IsAssignStationRequest(string orderNo) {
            this.orderNo = orderNo;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="IsAssignStationResponse", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class IsAssignStationResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        public bool IsAssignStationResult;
        
        public IsAssignStationResponse() {
        }
        
        public IsAssignStationResponse(bool IsAssignStationResult) {
            this.IsAssignStationResult = IsAssignStationResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="GetAssignDistributionOrders", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class GetAssignDistributionOrdersRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public Vancl.TMS.BLL.OrdersForWdsAssignService.DQQueryCondition condition;
        
        public GetAssignDistributionOrdersRequest() {
        }
        
        public GetAssignDistributionOrdersRequest(Vancl.TMS.BLL.OrdersForWdsAssignService.DQQueryCondition condition) {
            this.condition = condition;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="GetAssignDistributionOrdersResponse", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class GetAssignDistributionOrdersResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public System.Data.DataTable GetAssignDistributionOrdersResult;
        
        public GetAssignDistributionOrdersResponse() {
        }
        
        public GetAssignDistributionOrdersResponse(System.Data.DataTable GetAssignDistributionOrdersResult) {
            this.GetAssignDistributionOrdersResult = GetAssignDistributionOrdersResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="GetAssignStationOrders", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class GetAssignStationOrdersRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public Vancl.TMS.BLL.OrdersForWdsAssignService.SQQueryCondition condition;
        
        public GetAssignStationOrdersRequest() {
        }
        
        public GetAssignStationOrdersRequest(Vancl.TMS.BLL.OrdersForWdsAssignService.SQQueryCondition condition) {
            this.condition = condition;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="GetAssignStationOrdersResponse", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class GetAssignStationOrdersResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public System.Data.DataTable GetAssignStationOrdersResult;
        
        public GetAssignStationOrdersResponse() {
        }
        
        public GetAssignStationOrdersResponse(System.Data.DataTable GetAssignStationOrdersResult) {
            this.GetAssignStationOrdersResult = GetAssignStationOrdersResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="OutBound", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class OutBoundRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string orderNo;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=1)]
        public int status;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=2)]
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string currentDistributionCode;
        
        public OutBoundRequest() {
        }
        
        public OutBoundRequest(string orderNo, int status, string currentDistributionCode) {
            this.orderNo = orderNo;
            this.status = status;
            this.currentDistributionCode = currentDistributionCode;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="OutBoundResponse", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class OutBoundResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        public bool OutBoundResult;
        
        public OutBoundResponse() {
        }
        
        public OutBoundResponse(bool OutBoundResult) {
            this.OutBoundResult = OutBoundResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="AssignDistributionChange", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class AssignDistributionChangeRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string orderNo;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=1)]
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string currentDistributionCode;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=2)]
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string assignDistributionCode;
        
        public AssignDistributionChangeRequest() {
        }
        
        public AssignDistributionChangeRequest(string orderNo, string currentDistributionCode, string assignDistributionCode) {
            this.orderNo = orderNo;
            this.currentDistributionCode = currentDistributionCode;
            this.assignDistributionCode = assignDistributionCode;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="AssignDistributionChangeResponse", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class AssignDistributionChangeResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        public bool AssignDistributionChangeResult;
        
        public AssignDistributionChangeResponse() {
        }
        
        public AssignDistributionChangeResponse(bool AssignDistributionChangeResult) {
            this.AssignDistributionChangeResult = AssignDistributionChangeResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="IsOutBound", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class IsOutBoundRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string orderno;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=1)]
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string currentDistributionCode;
        
        public IsOutBoundRequest() {
        }
        
        public IsOutBoundRequest(string orderno, string currentDistributionCode) {
            this.orderno = orderno;
            this.currentDistributionCode = currentDistributionCode;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="IsOutBoundResponse", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class IsOutBoundResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        public bool IsOutBoundResult;
        
        public IsOutBoundResponse() {
        }
        
        public IsOutBoundResponse(bool IsOutBoundResult) {
            this.IsOutBoundResult = IsOutBoundResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="AssignFail", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class AssignFailRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string orderNo;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=1)]
        public int failAssignType;
        
        public AssignFailRequest() {
        }
        
        public AssignFailRequest(string orderNo, int failAssignType) {
            this.orderNo = orderNo;
            this.failAssignType = failAssignType;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="AssignFailResponse", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class AssignFailResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        public bool AssignFailResult;
        
        public AssignFailResponse() {
        }
        
        public AssignFailResponse(bool AssignFailResult) {
            this.AssignFailResult = AssignFailResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="GetAssignDistribution", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class GetAssignDistributionRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string orderNo;
        
        public GetAssignDistributionRequest() {
        }
        
        public GetAssignDistributionRequest(string orderNo) {
            this.orderNo = orderNo;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="GetAssignDistributionResponse", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class GetAssignDistributionResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string GetAssignDistributionResult;
        
        public GetAssignDistributionResponse() {
        }
        
        public GetAssignDistributionResponse(string GetAssignDistributionResult) {
            this.GetAssignDistributionResult = GetAssignDistributionResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="GetAssignStation", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class GetAssignStationRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string orderNo;
        
        public GetAssignStationRequest() {
        }
        
        public GetAssignStationRequest(string orderNo) {
            this.orderNo = orderNo;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="GetAssignStationResponse", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class GetAssignStationResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        public int GetAssignStationResult;
        
        public GetAssignStationResponse() {
        }
        
        public GetAssignStationResponse(int GetAssignStationResult) {
            this.GetAssignStationResult = GetAssignStationResult;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IOrdersForWdsAssignChannel : Vancl.TMS.BLL.OrdersForWdsAssignService.IOrdersForWdsAssign, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class OrdersForWdsAssignClient : System.ServiceModel.ClientBase<Vancl.TMS.BLL.OrdersForWdsAssignService.IOrdersForWdsAssign>, Vancl.TMS.BLL.OrdersForWdsAssignService.IOrdersForWdsAssign {
        
        public OrdersForWdsAssignClient() {
        }
        
        public OrdersForWdsAssignClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public OrdersForWdsAssignClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public OrdersForWdsAssignClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public OrdersForWdsAssignClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Vancl.TMS.BLL.OrdersForWdsAssignService.GetWaitAssignDistributionOrdersResponse Vancl.TMS.BLL.OrdersForWdsAssignService.IOrdersForWdsAssign.GetWaitAssignDistributionOrders(Vancl.TMS.BLL.OrdersForWdsAssignService.GetWaitAssignDistributionOrdersRequest request) {
            return base.Channel.GetWaitAssignDistributionOrders(request);
        }
        
        public Vancl.TMS.BLL.OrdersForWdsAssignService.AssignInfoForWds[] GetWaitAssignDistributionOrders(int assignStatus, int top) {
            Vancl.TMS.BLL.OrdersForWdsAssignService.GetWaitAssignDistributionOrdersRequest inValue = new Vancl.TMS.BLL.OrdersForWdsAssignService.GetWaitAssignDistributionOrdersRequest();
            inValue.assignStatus = assignStatus;
            inValue.top = top;
            Vancl.TMS.BLL.OrdersForWdsAssignService.GetWaitAssignDistributionOrdersResponse retVal = ((Vancl.TMS.BLL.OrdersForWdsAssignService.IOrdersForWdsAssign)(this)).GetWaitAssignDistributionOrders(inValue);
            return retVal.GetWaitAssignDistributionOrdersResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Vancl.TMS.BLL.OrdersForWdsAssignService.GetWaitAssignStationOrdersResponse Vancl.TMS.BLL.OrdersForWdsAssignService.IOrdersForWdsAssign.GetWaitAssignStationOrders(Vancl.TMS.BLL.OrdersForWdsAssignService.GetWaitAssignStationOrdersRequest request) {
            return base.Channel.GetWaitAssignStationOrders(request);
        }
        
        public Vancl.TMS.BLL.OrdersForWdsAssignService.AssignInfoForWds[] GetWaitAssignStationOrders(int assignStatus, int top) {
            Vancl.TMS.BLL.OrdersForWdsAssignService.GetWaitAssignStationOrdersRequest inValue = new Vancl.TMS.BLL.OrdersForWdsAssignService.GetWaitAssignStationOrdersRequest();
            inValue.assignStatus = assignStatus;
            inValue.top = top;
            Vancl.TMS.BLL.OrdersForWdsAssignService.GetWaitAssignStationOrdersResponse retVal = ((Vancl.TMS.BLL.OrdersForWdsAssignService.IOrdersForWdsAssign)(this)).GetWaitAssignStationOrders(inValue);
            return retVal.GetWaitAssignStationOrdersResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Vancl.TMS.BLL.OrdersForWdsAssignService.AssignDistributionResponse Vancl.TMS.BLL.OrdersForWdsAssignService.IOrdersForWdsAssign.AssignDistribution(Vancl.TMS.BLL.OrdersForWdsAssignService.AssignDistributionRequest request) {
            return base.Channel.AssignDistribution(request);
        }
        
        public int AssignDistribution(string orderNo, string fromDistributionCode, string curDistributionCode, int assignType) {
            Vancl.TMS.BLL.OrdersForWdsAssignService.AssignDistributionRequest inValue = new Vancl.TMS.BLL.OrdersForWdsAssignService.AssignDistributionRequest();
            inValue.orderNo = orderNo;
            inValue.fromDistributionCode = fromDistributionCode;
            inValue.curDistributionCode = curDistributionCode;
            inValue.assignType = assignType;
            Vancl.TMS.BLL.OrdersForWdsAssignService.AssignDistributionResponse retVal = ((Vancl.TMS.BLL.OrdersForWdsAssignService.IOrdersForWdsAssign)(this)).AssignDistribution(inValue);
            return retVal.AssignDistributionResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Vancl.TMS.BLL.OrdersForWdsAssignService.AssignStationResponse Vancl.TMS.BLL.OrdersForWdsAssignService.IOrdersForWdsAssign.AssignStation(Vancl.TMS.BLL.OrdersForWdsAssignService.AssignStationRequest request) {
            return base.Channel.AssignStation(request);
        }
        
        public int AssignStation(string orderNo, int stationId, int assignType) {
            Vancl.TMS.BLL.OrdersForWdsAssignService.AssignStationRequest inValue = new Vancl.TMS.BLL.OrdersForWdsAssignService.AssignStationRequest();
            inValue.orderNo = orderNo;
            inValue.stationId = stationId;
            inValue.assignType = assignType;
            Vancl.TMS.BLL.OrdersForWdsAssignService.AssignStationResponse retVal = ((Vancl.TMS.BLL.OrdersForWdsAssignService.IOrdersForWdsAssign)(this)).AssignStation(inValue);
            return retVal.AssignStationResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Vancl.TMS.BLL.OrdersForWdsAssignService.IsAssignDistributionResponse Vancl.TMS.BLL.OrdersForWdsAssignService.IOrdersForWdsAssign.IsAssignDistribution(Vancl.TMS.BLL.OrdersForWdsAssignService.IsAssignDistributionRequest request) {
            return base.Channel.IsAssignDistribution(request);
        }
        
        public bool IsAssignDistribution(string orderNo) {
            Vancl.TMS.BLL.OrdersForWdsAssignService.IsAssignDistributionRequest inValue = new Vancl.TMS.BLL.OrdersForWdsAssignService.IsAssignDistributionRequest();
            inValue.orderNo = orderNo;
            Vancl.TMS.BLL.OrdersForWdsAssignService.IsAssignDistributionResponse retVal = ((Vancl.TMS.BLL.OrdersForWdsAssignService.IOrdersForWdsAssign)(this)).IsAssignDistribution(inValue);
            return retVal.IsAssignDistributionResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Vancl.TMS.BLL.OrdersForWdsAssignService.IsAssignStationResponse Vancl.TMS.BLL.OrdersForWdsAssignService.IOrdersForWdsAssign.IsAssignStation(Vancl.TMS.BLL.OrdersForWdsAssignService.IsAssignStationRequest request) {
            return base.Channel.IsAssignStation(request);
        }
        
        public bool IsAssignStation(string orderNo) {
            Vancl.TMS.BLL.OrdersForWdsAssignService.IsAssignStationRequest inValue = new Vancl.TMS.BLL.OrdersForWdsAssignService.IsAssignStationRequest();
            inValue.orderNo = orderNo;
            Vancl.TMS.BLL.OrdersForWdsAssignService.IsAssignStationResponse retVal = ((Vancl.TMS.BLL.OrdersForWdsAssignService.IOrdersForWdsAssign)(this)).IsAssignStation(inValue);
            return retVal.IsAssignStationResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Vancl.TMS.BLL.OrdersForWdsAssignService.GetAssignDistributionOrdersResponse Vancl.TMS.BLL.OrdersForWdsAssignService.IOrdersForWdsAssign.GetAssignDistributionOrders(Vancl.TMS.BLL.OrdersForWdsAssignService.GetAssignDistributionOrdersRequest request) {
            return base.Channel.GetAssignDistributionOrders(request);
        }
        
        public System.Data.DataTable GetAssignDistributionOrders(Vancl.TMS.BLL.OrdersForWdsAssignService.DQQueryCondition condition) {
            Vancl.TMS.BLL.OrdersForWdsAssignService.GetAssignDistributionOrdersRequest inValue = new Vancl.TMS.BLL.OrdersForWdsAssignService.GetAssignDistributionOrdersRequest();
            inValue.condition = condition;
            Vancl.TMS.BLL.OrdersForWdsAssignService.GetAssignDistributionOrdersResponse retVal = ((Vancl.TMS.BLL.OrdersForWdsAssignService.IOrdersForWdsAssign)(this)).GetAssignDistributionOrders(inValue);
            return retVal.GetAssignDistributionOrdersResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Vancl.TMS.BLL.OrdersForWdsAssignService.GetAssignStationOrdersResponse Vancl.TMS.BLL.OrdersForWdsAssignService.IOrdersForWdsAssign.GetAssignStationOrders(Vancl.TMS.BLL.OrdersForWdsAssignService.GetAssignStationOrdersRequest request) {
            return base.Channel.GetAssignStationOrders(request);
        }
        
        public System.Data.DataTable GetAssignStationOrders(Vancl.TMS.BLL.OrdersForWdsAssignService.SQQueryCondition condition) {
            Vancl.TMS.BLL.OrdersForWdsAssignService.GetAssignStationOrdersRequest inValue = new Vancl.TMS.BLL.OrdersForWdsAssignService.GetAssignStationOrdersRequest();
            inValue.condition = condition;
            Vancl.TMS.BLL.OrdersForWdsAssignService.GetAssignStationOrdersResponse retVal = ((Vancl.TMS.BLL.OrdersForWdsAssignService.IOrdersForWdsAssign)(this)).GetAssignStationOrders(inValue);
            return retVal.GetAssignStationOrdersResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Vancl.TMS.BLL.OrdersForWdsAssignService.OutBoundResponse Vancl.TMS.BLL.OrdersForWdsAssignService.IOrdersForWdsAssign.OutBound(Vancl.TMS.BLL.OrdersForWdsAssignService.OutBoundRequest request) {
            return base.Channel.OutBound(request);
        }
        
        public bool OutBound(string orderNo, int status, string currentDistributionCode) {
            Vancl.TMS.BLL.OrdersForWdsAssignService.OutBoundRequest inValue = new Vancl.TMS.BLL.OrdersForWdsAssignService.OutBoundRequest();
            inValue.orderNo = orderNo;
            inValue.status = status;
            inValue.currentDistributionCode = currentDistributionCode;
            Vancl.TMS.BLL.OrdersForWdsAssignService.OutBoundResponse retVal = ((Vancl.TMS.BLL.OrdersForWdsAssignService.IOrdersForWdsAssign)(this)).OutBound(inValue);
            return retVal.OutBoundResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Vancl.TMS.BLL.OrdersForWdsAssignService.AssignDistributionChangeResponse Vancl.TMS.BLL.OrdersForWdsAssignService.IOrdersForWdsAssign.AssignDistributionChange(Vancl.TMS.BLL.OrdersForWdsAssignService.AssignDistributionChangeRequest request) {
            return base.Channel.AssignDistributionChange(request);
        }
        
        public bool AssignDistributionChange(string orderNo, string currentDistributionCode, string assignDistributionCode) {
            Vancl.TMS.BLL.OrdersForWdsAssignService.AssignDistributionChangeRequest inValue = new Vancl.TMS.BLL.OrdersForWdsAssignService.AssignDistributionChangeRequest();
            inValue.orderNo = orderNo;
            inValue.currentDistributionCode = currentDistributionCode;
            inValue.assignDistributionCode = assignDistributionCode;
            Vancl.TMS.BLL.OrdersForWdsAssignService.AssignDistributionChangeResponse retVal = ((Vancl.TMS.BLL.OrdersForWdsAssignService.IOrdersForWdsAssign)(this)).AssignDistributionChange(inValue);
            return retVal.AssignDistributionChangeResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Vancl.TMS.BLL.OrdersForWdsAssignService.IsOutBoundResponse Vancl.TMS.BLL.OrdersForWdsAssignService.IOrdersForWdsAssign.IsOutBound(Vancl.TMS.BLL.OrdersForWdsAssignService.IsOutBoundRequest request) {
            return base.Channel.IsOutBound(request);
        }
        
        public bool IsOutBound(string orderno, string currentDistributionCode) {
            Vancl.TMS.BLL.OrdersForWdsAssignService.IsOutBoundRequest inValue = new Vancl.TMS.BLL.OrdersForWdsAssignService.IsOutBoundRequest();
            inValue.orderno = orderno;
            inValue.currentDistributionCode = currentDistributionCode;
            Vancl.TMS.BLL.OrdersForWdsAssignService.IsOutBoundResponse retVal = ((Vancl.TMS.BLL.OrdersForWdsAssignService.IOrdersForWdsAssign)(this)).IsOutBound(inValue);
            return retVal.IsOutBoundResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Vancl.TMS.BLL.OrdersForWdsAssignService.AssignFailResponse Vancl.TMS.BLL.OrdersForWdsAssignService.IOrdersForWdsAssign.AssignFail(Vancl.TMS.BLL.OrdersForWdsAssignService.AssignFailRequest request) {
            return base.Channel.AssignFail(request);
        }
        
        public bool AssignFail(string orderNo, int failAssignType) {
            Vancl.TMS.BLL.OrdersForWdsAssignService.AssignFailRequest inValue = new Vancl.TMS.BLL.OrdersForWdsAssignService.AssignFailRequest();
            inValue.orderNo = orderNo;
            inValue.failAssignType = failAssignType;
            Vancl.TMS.BLL.OrdersForWdsAssignService.AssignFailResponse retVal = ((Vancl.TMS.BLL.OrdersForWdsAssignService.IOrdersForWdsAssign)(this)).AssignFail(inValue);
            return retVal.AssignFailResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Vancl.TMS.BLL.OrdersForWdsAssignService.GetAssignDistributionResponse Vancl.TMS.BLL.OrdersForWdsAssignService.IOrdersForWdsAssign.GetAssignDistribution(Vancl.TMS.BLL.OrdersForWdsAssignService.GetAssignDistributionRequest request) {
            return base.Channel.GetAssignDistribution(request);
        }
        
        public string GetAssignDistribution(string orderNo) {
            Vancl.TMS.BLL.OrdersForWdsAssignService.GetAssignDistributionRequest inValue = new Vancl.TMS.BLL.OrdersForWdsAssignService.GetAssignDistributionRequest();
            inValue.orderNo = orderNo;
            Vancl.TMS.BLL.OrdersForWdsAssignService.GetAssignDistributionResponse retVal = ((Vancl.TMS.BLL.OrdersForWdsAssignService.IOrdersForWdsAssign)(this)).GetAssignDistribution(inValue);
            return retVal.GetAssignDistributionResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Vancl.TMS.BLL.OrdersForWdsAssignService.GetAssignStationResponse Vancl.TMS.BLL.OrdersForWdsAssignService.IOrdersForWdsAssign.GetAssignStation(Vancl.TMS.BLL.OrdersForWdsAssignService.GetAssignStationRequest request) {
            return base.Channel.GetAssignStation(request);
        }
        
        public int GetAssignStation(string orderNo) {
            Vancl.TMS.BLL.OrdersForWdsAssignService.GetAssignStationRequest inValue = new Vancl.TMS.BLL.OrdersForWdsAssignService.GetAssignStationRequest();
            inValue.orderNo = orderNo;
            Vancl.TMS.BLL.OrdersForWdsAssignService.GetAssignStationResponse retVal = ((Vancl.TMS.BLL.OrdersForWdsAssignService.IOrdersForWdsAssign)(this)).GetAssignStation(inValue);
            return retVal.GetAssignStationResult;
        }
    }
}
