//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.269
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Vancl.TMS.BLL.Proxy.TMSAPIService {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="TMSEntranceModel", Namespace="http://schemas.datacontract.org/2004/07/Vancl.TMS.Model.Delivery.DataInteraction." +
        "Entrance")]
    [System.SerializableAttribute()]
    public partial class TMSEntranceModel : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ArrivalField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string BatchNoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private Vancl.TMS.BLL.Proxy.TMSAPIService.EnumsGoodsType ContentTypeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string DepartureField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private Vancl.TMS.BLL.Proxy.TMSAPIService.BillDetailModel[] DetailField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private Vancl.TMS.BLL.Proxy.TMSAPIService.EnumsTMSEntranceSource SourceField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private decimal TotalAmountField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int TotalCountField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private decimal WeightField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Arrival {
            get {
                return this.ArrivalField;
            }
            set {
                if ((object.ReferenceEquals(this.ArrivalField, value) != true)) {
                    this.ArrivalField = value;
                    this.RaisePropertyChanged("Arrival");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string BatchNo {
            get {
                return this.BatchNoField;
            }
            set {
                if ((object.ReferenceEquals(this.BatchNoField, value) != true)) {
                    this.BatchNoField = value;
                    this.RaisePropertyChanged("BatchNo");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public Vancl.TMS.BLL.Proxy.TMSAPIService.EnumsGoodsType ContentType {
            get {
                return this.ContentTypeField;
            }
            set {
                if ((this.ContentTypeField.Equals(value) != true)) {
                    this.ContentTypeField = value;
                    this.RaisePropertyChanged("ContentType");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Departure {
            get {
                return this.DepartureField;
            }
            set {
                if ((object.ReferenceEquals(this.DepartureField, value) != true)) {
                    this.DepartureField = value;
                    this.RaisePropertyChanged("Departure");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public Vancl.TMS.BLL.Proxy.TMSAPIService.BillDetailModel[] Detail {
            get {
                return this.DetailField;
            }
            set {
                if ((object.ReferenceEquals(this.DetailField, value) != true)) {
                    this.DetailField = value;
                    this.RaisePropertyChanged("Detail");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public Vancl.TMS.BLL.Proxy.TMSAPIService.EnumsTMSEntranceSource Source {
            get {
                return this.SourceField;
            }
            set {
                if ((this.SourceField.Equals(value) != true)) {
                    this.SourceField = value;
                    this.RaisePropertyChanged("Source");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public decimal TotalAmount {
            get {
                return this.TotalAmountField;
            }
            set {
                if ((this.TotalAmountField.Equals(value) != true)) {
                    this.TotalAmountField = value;
                    this.RaisePropertyChanged("TotalAmount");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int TotalCount {
            get {
                return this.TotalCountField;
            }
            set {
                if ((this.TotalCountField.Equals(value) != true)) {
                    this.TotalCountField = value;
                    this.RaisePropertyChanged("TotalCount");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public decimal Weight {
            get {
                return this.WeightField;
            }
            set {
                if ((this.WeightField.Equals(value) != true)) {
                    this.WeightField = value;
                    this.RaisePropertyChanged("Weight");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.FlagsAttribute()]
    [System.Runtime.Serialization.DataContractAttribute(Name="Enums.GoodsType", Namespace="http://schemas.datacontract.org/2004/07/Vancl.TMS.Model.Common")]
    public enum EnumsGoodsType : int {
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Normal = 1,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Contraband = 2,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Frangible = 4,
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="BillDetailModel", Namespace="http://schemas.datacontract.org/2004/07/Vancl.TMS.Model.Delivery.DataInteraction." +
        "Entrance")]
    [System.SerializableAttribute()]
    public partial class BillDetailModel : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private Vancl.TMS.BLL.Proxy.TMSAPIService.EnumsBillType BillTypeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string CustomerOrderField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string FormCodeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private Vancl.TMS.BLL.Proxy.TMSAPIService.EnumsGoodsType GoodsTypeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private decimal PriceField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public Vancl.TMS.BLL.Proxy.TMSAPIService.EnumsBillType BillType {
            get {
                return this.BillTypeField;
            }
            set {
                if ((this.BillTypeField.Equals(value) != true)) {
                    this.BillTypeField = value;
                    this.RaisePropertyChanged("BillType");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string CustomerOrder {
            get {
                return this.CustomerOrderField;
            }
            set {
                if ((object.ReferenceEquals(this.CustomerOrderField, value) != true)) {
                    this.CustomerOrderField = value;
                    this.RaisePropertyChanged("CustomerOrder");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string FormCode {
            get {
                return this.FormCodeField;
            }
            set {
                if ((object.ReferenceEquals(this.FormCodeField, value) != true)) {
                    this.FormCodeField = value;
                    this.RaisePropertyChanged("FormCode");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public Vancl.TMS.BLL.Proxy.TMSAPIService.EnumsGoodsType GoodsType {
            get {
                return this.GoodsTypeField;
            }
            set {
                if ((this.GoodsTypeField.Equals(value) != true)) {
                    this.GoodsTypeField = value;
                    this.RaisePropertyChanged("GoodsType");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public decimal Price {
            get {
                return this.PriceField;
            }
            set {
                if ((this.PriceField.Equals(value) != true)) {
                    this.PriceField = value;
                    this.RaisePropertyChanged("Price");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Enums.TMSEntranceSource", Namespace="http://schemas.datacontract.org/2004/07/Vancl.TMS.Model.Common")]
    public enum EnumsTMSEntranceSource : int {
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        VANCL = 0,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        VJIA = 1,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        SortingOutbound = 2,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        SortingPacking = 3,
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Enums.BillType", Namespace="http://schemas.datacontract.org/2004/07/Vancl.TMS.Model.Common")]
    public enum EnumsBillType : int {
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Normal = 0,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Exchange = 1,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Return = 2,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        SignReturn = 3,
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="ResultModel", Namespace="http://schemas.datacontract.org/2004/07/Vancl.TMS.Model.Common")]
    [System.SerializableAttribute()]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(Vancl.TMS.BLL.Proxy.TMSAPIService.ViewInboundSimpleModel))]
    public partial class ResultModel : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private bool IsSuccessField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string MessageField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool IsSuccess {
            get {
                return this.IsSuccessField;
            }
            set {
                if ((this.IsSuccessField.Equals(value) != true)) {
                    this.IsSuccessField = value;
                    this.RaisePropertyChanged("IsSuccess");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Message {
            get {
                return this.MessageField;
            }
            set {
                if ((object.ReferenceEquals(this.MessageField, value) != true)) {
                    this.MessageField = value;
                    this.RaisePropertyChanged("Message");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="ViewInboundSimpleModel", Namespace="http://schemas.datacontract.org/2004/07/Vancl.TMS.Model.Sorting.Inbound")]
    [System.SerializableAttribute()]
    public partial class ViewInboundSimpleModel : Vancl.TMS.BLL.Proxy.TMSAPIService.ResultModel {
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string CustomerOrderField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string FormCodeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int InboundCountField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string CustomerOrder {
            get {
                return this.CustomerOrderField;
            }
            set {
                if ((object.ReferenceEquals(this.CustomerOrderField, value) != true)) {
                    this.CustomerOrderField = value;
                    this.RaisePropertyChanged("CustomerOrder");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string FormCode {
            get {
                return this.FormCodeField;
            }
            set {
                if ((object.ReferenceEquals(this.FormCodeField, value) != true)) {
                    this.FormCodeField = value;
                    this.RaisePropertyChanged("FormCode");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int InboundCount {
            get {
                return this.InboundCountField;
            }
            set {
                if ((this.InboundCountField.Equals(value) != true)) {
                    this.InboundCountField = value;
                    this.RaisePropertyChanged("InboundCount");
                }
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="SortCenterSimpleArgModel", Namespace="http://schemas.datacontract.org/2004/07/Vancl.TMS.Model.Sorting.Common")]
    [System.SerializableAttribute()]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(Vancl.TMS.BLL.Proxy.TMSAPIService.InboundSimpleArgModel))]
    public partial class SortCenterSimpleArgModel : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string FormCodeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private Vancl.TMS.BLL.Proxy.TMSAPIService.EnumsSortCenterFormType FormTypeField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string FormCode {
            get {
                return this.FormCodeField;
            }
            set {
                if ((object.ReferenceEquals(this.FormCodeField, value) != true)) {
                    this.FormCodeField = value;
                    this.RaisePropertyChanged("FormCode");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public Vancl.TMS.BLL.Proxy.TMSAPIService.EnumsSortCenterFormType FormType {
            get {
                return this.FormTypeField;
            }
            set {
                if ((this.FormTypeField.Equals(value) != true)) {
                    this.FormTypeField = value;
                    this.RaisePropertyChanged("FormType");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="InboundSimpleArgModel", Namespace="http://schemas.datacontract.org/2004/07/Vancl.TMS.Model.Sorting.Inbound")]
    [System.SerializableAttribute()]
    public partial class InboundSimpleArgModel : Vancl.TMS.BLL.Proxy.TMSAPIService.SortCenterSimpleArgModel {
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private bool IsLimitedQuantityField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int LimitedInboundCountField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private Vancl.TMS.BLL.Proxy.TMSAPIService.SortCenterUserModel OpUserField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private Vancl.TMS.BLL.Proxy.TMSAPIService.InboundPreConditionModel PreConditionField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private Vancl.TMS.BLL.Proxy.TMSAPIService.SortCenterToStationModel ToStationField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool IsLimitedQuantity {
            get {
                return this.IsLimitedQuantityField;
            }
            set {
                if ((this.IsLimitedQuantityField.Equals(value) != true)) {
                    this.IsLimitedQuantityField = value;
                    this.RaisePropertyChanged("IsLimitedQuantity");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int LimitedInboundCount {
            get {
                return this.LimitedInboundCountField;
            }
            set {
                if ((this.LimitedInboundCountField.Equals(value) != true)) {
                    this.LimitedInboundCountField = value;
                    this.RaisePropertyChanged("LimitedInboundCount");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public Vancl.TMS.BLL.Proxy.TMSAPIService.SortCenterUserModel OpUser {
            get {
                return this.OpUserField;
            }
            set {
                if ((object.ReferenceEquals(this.OpUserField, value) != true)) {
                    this.OpUserField = value;
                    this.RaisePropertyChanged("OpUser");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public Vancl.TMS.BLL.Proxy.TMSAPIService.InboundPreConditionModel PreCondition {
            get {
                return this.PreConditionField;
            }
            set {
                if ((object.ReferenceEquals(this.PreConditionField, value) != true)) {
                    this.PreConditionField = value;
                    this.RaisePropertyChanged("PreCondition");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public Vancl.TMS.BLL.Proxy.TMSAPIService.SortCenterToStationModel ToStation {
            get {
                return this.ToStationField;
            }
            set {
                if ((object.ReferenceEquals(this.ToStationField, value) != true)) {
                    this.ToStationField = value;
                    this.RaisePropertyChanged("ToStation");
                }
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Enums.SortCenterFormType", Namespace="http://schemas.datacontract.org/2004/07/Vancl.TMS.Model.Common")]
    public enum EnumsSortCenterFormType : int {
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Waybill = 0,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Order = 1,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        DeliverCode = 2,
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="SortCenterUserModel", Namespace="http://schemas.datacontract.org/2004/07/Vancl.TMS.Model.Sorting.Common")]
    [System.SerializableAttribute()]
    public partial class SortCenterUserModel : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private Vancl.TMS.BLL.Proxy.TMSAPIService.EnumsCompanyFlag CompanyFlagField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string CompanyNameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string DistributionCodeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string DistributionMnemonicNameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string DistributionNameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<int> ExpressIdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string MnemonicCodeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string MnemonicNameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int UserIdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string UserNameField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public Vancl.TMS.BLL.Proxy.TMSAPIService.EnumsCompanyFlag CompanyFlag {
            get {
                return this.CompanyFlagField;
            }
            set {
                if ((this.CompanyFlagField.Equals(value) != true)) {
                    this.CompanyFlagField = value;
                    this.RaisePropertyChanged("CompanyFlag");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string CompanyName {
            get {
                return this.CompanyNameField;
            }
            set {
                if ((object.ReferenceEquals(this.CompanyNameField, value) != true)) {
                    this.CompanyNameField = value;
                    this.RaisePropertyChanged("CompanyName");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string DistributionCode {
            get {
                return this.DistributionCodeField;
            }
            set {
                if ((object.ReferenceEquals(this.DistributionCodeField, value) != true)) {
                    this.DistributionCodeField = value;
                    this.RaisePropertyChanged("DistributionCode");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string DistributionMnemonicName {
            get {
                return this.DistributionMnemonicNameField;
            }
            set {
                if ((object.ReferenceEquals(this.DistributionMnemonicNameField, value) != true)) {
                    this.DistributionMnemonicNameField = value;
                    this.RaisePropertyChanged("DistributionMnemonicName");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string DistributionName {
            get {
                return this.DistributionNameField;
            }
            set {
                if ((object.ReferenceEquals(this.DistributionNameField, value) != true)) {
                    this.DistributionNameField = value;
                    this.RaisePropertyChanged("DistributionName");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<int> ExpressId {
            get {
                return this.ExpressIdField;
            }
            set {
                if ((this.ExpressIdField.Equals(value) != true)) {
                    this.ExpressIdField = value;
                    this.RaisePropertyChanged("ExpressId");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string MnemonicCode {
            get {
                return this.MnemonicCodeField;
            }
            set {
                if ((object.ReferenceEquals(this.MnemonicCodeField, value) != true)) {
                    this.MnemonicCodeField = value;
                    this.RaisePropertyChanged("MnemonicCode");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string MnemonicName {
            get {
                return this.MnemonicNameField;
            }
            set {
                if ((object.ReferenceEquals(this.MnemonicNameField, value) != true)) {
                    this.MnemonicNameField = value;
                    this.RaisePropertyChanged("MnemonicName");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int UserId {
            get {
                return this.UserIdField;
            }
            set {
                if ((this.UserIdField.Equals(value) != true)) {
                    this.UserIdField = value;
                    this.RaisePropertyChanged("UserId");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string UserName {
            get {
                return this.UserNameField;
            }
            set {
                if ((object.ReferenceEquals(this.UserNameField, value) != true)) {
                    this.UserNameField = value;
                    this.RaisePropertyChanged("UserName");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="InboundPreConditionModel", Namespace="http://schemas.datacontract.org/2004/07/Vancl.TMS.Model.Sorting.Inbound")]
    [System.SerializableAttribute()]
    public partial class InboundPreConditionModel : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private Vancl.TMS.BLL.Proxy.TMSAPIService.EnumsBillStatus PreStatusField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public Vancl.TMS.BLL.Proxy.TMSAPIService.EnumsBillStatus PreStatus {
            get {
                return this.PreStatusField;
            }
            set {
                if ((this.PreStatusField.Equals(value) != true)) {
                    this.PreStatusField = value;
                    this.RaisePropertyChanged("PreStatus");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="SortCenterToStationModel", Namespace="http://schemas.datacontract.org/2004/07/Vancl.TMS.Model.Sorting.Common")]
    [System.SerializableAttribute()]
    public partial class SortCenterToStationModel : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private Vancl.TMS.BLL.Proxy.TMSAPIService.EnumsCompanyFlag CompanyFlagField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string DistributionCodeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int ExpressCompanyIDField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string MnemonicNameField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public Vancl.TMS.BLL.Proxy.TMSAPIService.EnumsCompanyFlag CompanyFlag {
            get {
                return this.CompanyFlagField;
            }
            set {
                if ((this.CompanyFlagField.Equals(value) != true)) {
                    this.CompanyFlagField = value;
                    this.RaisePropertyChanged("CompanyFlag");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string DistributionCode {
            get {
                return this.DistributionCodeField;
            }
            set {
                if ((object.ReferenceEquals(this.DistributionCodeField, value) != true)) {
                    this.DistributionCodeField = value;
                    this.RaisePropertyChanged("DistributionCode");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int ExpressCompanyID {
            get {
                return this.ExpressCompanyIDField;
            }
            set {
                if ((this.ExpressCompanyIDField.Equals(value) != true)) {
                    this.ExpressCompanyIDField = value;
                    this.RaisePropertyChanged("ExpressCompanyID");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string MnemonicName {
            get {
                return this.MnemonicNameField;
            }
            set {
                if ((object.ReferenceEquals(this.MnemonicNameField, value) != true)) {
                    this.MnemonicNameField = value;
                    this.RaisePropertyChanged("MnemonicName");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Enums.CompanyFlag", Namespace="http://schemas.datacontract.org/2004/07/Vancl.TMS.Model.Common")]
    public enum EnumsCompanyFlag : int {
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Administration = 0,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        SortingCenter = 1,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        DistributionStation = 2,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Distributor = 3,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        TransportationCenter = 4,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Merchant = 5,
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Enums.BillStatus", Namespace="http://schemas.datacontract.org/2004/07/Vancl.TMS.Model.Common")]
    public enum EnumsBillStatus : int {
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        InvalidBill = -9,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        ValidWaitingAssign = -5,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        GisAssigned = -4,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        WaitingInbound = -3,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Inbounded = -2,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        HaveBeenSorting = -1,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        InTransit = 0,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        InStation = 1,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Assigned = 2,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        DeliverySuccess = 3,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Delay = 4,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Rejected = 5,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        TransferringStation = 8,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Outbounded = 10,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Delivering = 22,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        ReturnBounded = 6,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        RefusedBounded = 7,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        ReturnOnStation = 11,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        ReturnInBound = 12,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        ReturnSignedBounded = 13,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        IntercityInTransit = 201,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        IntercityArrivaled = 202,
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="TMSAPIService.ITMSAPIService")]
    public interface ITMSAPIService {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ITMSAPIService/DataEntrance", ReplyAction="http://tempuri.org/ITMSAPIService/DataEntranceResponse")]
        Vancl.TMS.BLL.Proxy.TMSAPIService.ResultModel DataEntrance(Vancl.TMS.BLL.Proxy.TMSAPIService.TMSEntranceModel entranceModel);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ITMSAPIService/SimpleInbound", ReplyAction="http://tempuri.org/ITMSAPIService/SimpleInboundResponse")]
        Vancl.TMS.BLL.Proxy.TMSAPIService.ViewInboundSimpleModel SimpleInbound(Vancl.TMS.BLL.Proxy.TMSAPIService.InboundSimpleArgModel argument);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ITMSAPIService/GetInboundCount", ReplyAction="http://tempuri.org/ITMSAPIService/GetInboundCountResponse")]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(Vancl.TMS.BLL.Proxy.TMSAPIService.EnumsGoodsType))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(Vancl.TMS.BLL.Proxy.TMSAPIService.EnumsBillType))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(Vancl.TMS.BLL.Proxy.TMSAPIService.EnumsTMSEntranceSource))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(Vancl.TMS.BLL.Proxy.TMSAPIService.ResultModel))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(Vancl.TMS.BLL.Proxy.TMSAPIService.EnumsSortCenterFormType))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(Vancl.TMS.BLL.Proxy.TMSAPIService.EnumsCompanyFlag))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(Vancl.TMS.BLL.Proxy.TMSAPIService.EnumsBillStatus))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(Vancl.TMS.BLL.Proxy.TMSAPIService.TMSEntranceModel))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(Vancl.TMS.BLL.Proxy.TMSAPIService.BillDetailModel[]))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(Vancl.TMS.BLL.Proxy.TMSAPIService.BillDetailModel))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(Vancl.TMS.BLL.Proxy.TMSAPIService.SortCenterSimpleArgModel))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(Vancl.TMS.BLL.Proxy.TMSAPIService.SortCenterUserModel))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(Vancl.TMS.BLL.Proxy.TMSAPIService.SortCenterToStationModel))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(Vancl.TMS.BLL.Proxy.TMSAPIService.InboundSimpleArgModel))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(Vancl.TMS.BLL.Proxy.TMSAPIService.InboundPreConditionModel))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(Vancl.TMS.BLL.Proxy.TMSAPIService.ViewInboundSimpleModel))]
        int GetInboundCount(object argument);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ITMSAPIService/GetUserModel", ReplyAction="http://tempuri.org/ITMSAPIService/GetUserModelResponse")]
        Vancl.TMS.BLL.Proxy.TMSAPIService.SortCenterUserModel GetUserModel(int UserID);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ITMSAPIService/GetToStationModel", ReplyAction="http://tempuri.org/ITMSAPIService/GetToStationModelResponse")]
        Vancl.TMS.BLL.Proxy.TMSAPIService.SortCenterToStationModel GetToStationModel(int ArrivalID);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ITMSAPIService/GetPreCondition", ReplyAction="http://tempuri.org/ITMSAPIService/GetPreConditionResponse")]
        Vancl.TMS.BLL.Proxy.TMSAPIService.InboundPreConditionModel GetPreCondition(string DistributionCode);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface ITMSAPIServiceChannel : Vancl.TMS.BLL.Proxy.TMSAPIService.ITMSAPIService, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class TMSAPIServiceClient : System.ServiceModel.ClientBase<Vancl.TMS.BLL.Proxy.TMSAPIService.ITMSAPIService>, Vancl.TMS.BLL.Proxy.TMSAPIService.ITMSAPIService {
        
        public TMSAPIServiceClient() {
        }
        
        public TMSAPIServiceClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public TMSAPIServiceClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public TMSAPIServiceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public TMSAPIServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public Vancl.TMS.BLL.Proxy.TMSAPIService.ResultModel DataEntrance(Vancl.TMS.BLL.Proxy.TMSAPIService.TMSEntranceModel entranceModel) {
            return base.Channel.DataEntrance(entranceModel);
        }
        
        public Vancl.TMS.BLL.Proxy.TMSAPIService.ViewInboundSimpleModel SimpleInbound(Vancl.TMS.BLL.Proxy.TMSAPIService.InboundSimpleArgModel argument) {
            return base.Channel.SimpleInbound(argument);
        }
        
        public int GetInboundCount(object argument) {
            return base.Channel.GetInboundCount(argument);
        }
        
        public Vancl.TMS.BLL.Proxy.TMSAPIService.SortCenterUserModel GetUserModel(int UserID) {
            return base.Channel.GetUserModel(UserID);
        }
        
        public Vancl.TMS.BLL.Proxy.TMSAPIService.SortCenterToStationModel GetToStationModel(int ArrivalID) {
            return base.Channel.GetToStationModel(ArrivalID);
        }
        
        public Vancl.TMS.BLL.Proxy.TMSAPIService.InboundPreConditionModel GetPreCondition(string DistributionCode) {
            return base.Channel.GetPreCondition(DistributionCode);
        }
    }
}
