//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.17929
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Vancl.TMS.Schedule.Dps2TmsService.DpsOrdersForTMS {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="OrderForThirdParty", Namespace="http://schemas.datacontract.org/2004/07/Cloud.DPS.Model.OrderForThirdParty")]
    [System.SerializableAttribute()]
    public partial class OrderForThirdParty : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<decimal> AdditionalPriceField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string AddressField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string AddresseeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string AreaField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<int> AssignStatusField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<System.DateTime> AuditTimeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.DateTime BTimeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<decimal> BackFundField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<System.DateTime> BatchCreatTimeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string BatchPickCodeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private decimal BatchWeightField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<int> BoxCountField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string BoxNoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<bool> CallBeforeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string CashonDeliveryTypeNameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string CityField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string CommentField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<int> CreateByField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<int> CreateStationIdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<System.DateTime> CreateTimeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string CustomerBatchNOField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string DeliverCodeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<System.DateTime> DeliverTimeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string DistributionCodeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.DateTime ETimeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string EmailField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<int> ExpressCompanyIDField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ExpressCompanyNameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string FormCodeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string FromAddressField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string FromAreaField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string FromCityField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string FromProvinceField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string GoodsCategoryField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string GoodsPropertyField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string HouseCodeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int IncludeOrdersField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<bool> IsAutoAssignField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<bool> IsDeleteField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<bool> IsGisSuccessField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<bool> IsImportedField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<bool> IsSynField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string LineNumberField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string LogisticProviderIDField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<int> MarchartidField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string MobilePhoneField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<decimal> NeedFundField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private Vancl.TMS.Schedule.Dps2TmsService.DpsOrdersForTMS.OrderForThirdPartyDetails[] OrderForThirdPartyDetailListField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private long OrderForThirdPartyIdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string OrderIndexField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<decimal> OrderInfoVolumeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<int> OrderTypeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string OriginDepotNoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string PackageTypeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<decimal> PaidPriceField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<int> PaymentTypeIDField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string PerFormCodeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string PostalCodeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<decimal> PriceField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int ProjectExpressField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<decimal> ProtectedpriceField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ProvinceField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ReceiveTelField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<System.DateTime> ReceiveTimeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ReceiverField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string RelHouseCodeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ReplaceTypeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<decimal> ReturnSumField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string SendTimeTypeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<int> SortingCenterIdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string SortingCenterNameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<int> SourceField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<int> StatusField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string SupplierNameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private bool SupportDeliverCodeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int TimeTypeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<decimal> TransferPriceField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private bool UnGisAssignField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<int> UpdateByField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<int> UpdateStationIdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<System.DateTime> UpdateTimeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string UserNameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string WarehouseNameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string WaybillBoxModelField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<long> WaybillNoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<decimal> WeightField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<decimal> AdditionalPrice {
            get {
                return this.AdditionalPriceField;
            }
            set {
                if ((this.AdditionalPriceField.Equals(value) != true)) {
                    this.AdditionalPriceField = value;
                    this.RaisePropertyChanged("AdditionalPrice");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Address {
            get {
                return this.AddressField;
            }
            set {
                if ((object.ReferenceEquals(this.AddressField, value) != true)) {
                    this.AddressField = value;
                    this.RaisePropertyChanged("Address");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Addressee {
            get {
                return this.AddresseeField;
            }
            set {
                if ((object.ReferenceEquals(this.AddresseeField, value) != true)) {
                    this.AddresseeField = value;
                    this.RaisePropertyChanged("Addressee");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Area {
            get {
                return this.AreaField;
            }
            set {
                if ((object.ReferenceEquals(this.AreaField, value) != true)) {
                    this.AreaField = value;
                    this.RaisePropertyChanged("Area");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<int> AssignStatus {
            get {
                return this.AssignStatusField;
            }
            set {
                if ((this.AssignStatusField.Equals(value) != true)) {
                    this.AssignStatusField = value;
                    this.RaisePropertyChanged("AssignStatus");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<System.DateTime> AuditTime {
            get {
                return this.AuditTimeField;
            }
            set {
                if ((this.AuditTimeField.Equals(value) != true)) {
                    this.AuditTimeField = value;
                    this.RaisePropertyChanged("AuditTime");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime BTime {
            get {
                return this.BTimeField;
            }
            set {
                if ((this.BTimeField.Equals(value) != true)) {
                    this.BTimeField = value;
                    this.RaisePropertyChanged("BTime");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<decimal> BackFund {
            get {
                return this.BackFundField;
            }
            set {
                if ((this.BackFundField.Equals(value) != true)) {
                    this.BackFundField = value;
                    this.RaisePropertyChanged("BackFund");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<System.DateTime> BatchCreatTime {
            get {
                return this.BatchCreatTimeField;
            }
            set {
                if ((this.BatchCreatTimeField.Equals(value) != true)) {
                    this.BatchCreatTimeField = value;
                    this.RaisePropertyChanged("BatchCreatTime");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string BatchPickCode {
            get {
                return this.BatchPickCodeField;
            }
            set {
                if ((object.ReferenceEquals(this.BatchPickCodeField, value) != true)) {
                    this.BatchPickCodeField = value;
                    this.RaisePropertyChanged("BatchPickCode");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public decimal BatchWeight {
            get {
                return this.BatchWeightField;
            }
            set {
                if ((this.BatchWeightField.Equals(value) != true)) {
                    this.BatchWeightField = value;
                    this.RaisePropertyChanged("BatchWeight");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<int> BoxCount {
            get {
                return this.BoxCountField;
            }
            set {
                if ((this.BoxCountField.Equals(value) != true)) {
                    this.BoxCountField = value;
                    this.RaisePropertyChanged("BoxCount");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string BoxNo {
            get {
                return this.BoxNoField;
            }
            set {
                if ((object.ReferenceEquals(this.BoxNoField, value) != true)) {
                    this.BoxNoField = value;
                    this.RaisePropertyChanged("BoxNo");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<bool> CallBefore {
            get {
                return this.CallBeforeField;
            }
            set {
                if ((this.CallBeforeField.Equals(value) != true)) {
                    this.CallBeforeField = value;
                    this.RaisePropertyChanged("CallBefore");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string CashonDeliveryTypeName {
            get {
                return this.CashonDeliveryTypeNameField;
            }
            set {
                if ((object.ReferenceEquals(this.CashonDeliveryTypeNameField, value) != true)) {
                    this.CashonDeliveryTypeNameField = value;
                    this.RaisePropertyChanged("CashonDeliveryTypeName");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string City {
            get {
                return this.CityField;
            }
            set {
                if ((object.ReferenceEquals(this.CityField, value) != true)) {
                    this.CityField = value;
                    this.RaisePropertyChanged("City");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Comment {
            get {
                return this.CommentField;
            }
            set {
                if ((object.ReferenceEquals(this.CommentField, value) != true)) {
                    this.CommentField = value;
                    this.RaisePropertyChanged("Comment");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<int> CreateBy {
            get {
                return this.CreateByField;
            }
            set {
                if ((this.CreateByField.Equals(value) != true)) {
                    this.CreateByField = value;
                    this.RaisePropertyChanged("CreateBy");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<int> CreateStationId {
            get {
                return this.CreateStationIdField;
            }
            set {
                if ((this.CreateStationIdField.Equals(value) != true)) {
                    this.CreateStationIdField = value;
                    this.RaisePropertyChanged("CreateStationId");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<System.DateTime> CreateTime {
            get {
                return this.CreateTimeField;
            }
            set {
                if ((this.CreateTimeField.Equals(value) != true)) {
                    this.CreateTimeField = value;
                    this.RaisePropertyChanged("CreateTime");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string CustomerBatchNO {
            get {
                return this.CustomerBatchNOField;
            }
            set {
                if ((object.ReferenceEquals(this.CustomerBatchNOField, value) != true)) {
                    this.CustomerBatchNOField = value;
                    this.RaisePropertyChanged("CustomerBatchNO");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string DeliverCode {
            get {
                return this.DeliverCodeField;
            }
            set {
                if ((object.ReferenceEquals(this.DeliverCodeField, value) != true)) {
                    this.DeliverCodeField = value;
                    this.RaisePropertyChanged("DeliverCode");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<System.DateTime> DeliverTime {
            get {
                return this.DeliverTimeField;
            }
            set {
                if ((this.DeliverTimeField.Equals(value) != true)) {
                    this.DeliverTimeField = value;
                    this.RaisePropertyChanged("DeliverTime");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string DistributionCode {
            get {
                return this.DistributionCodeField;
            }
            set {
                if ((object.ReferenceEquals(this.DistributionCodeField, value) != true)) {
                    this.DistributionCodeField = value;
                    this.RaisePropertyChanged("DistributionCode");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime ETime {
            get {
                return this.ETimeField;
            }
            set {
                if ((this.ETimeField.Equals(value) != true)) {
                    this.ETimeField = value;
                    this.RaisePropertyChanged("ETime");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Email {
            get {
                return this.EmailField;
            }
            set {
                if ((object.ReferenceEquals(this.EmailField, value) != true)) {
                    this.EmailField = value;
                    this.RaisePropertyChanged("Email");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<int> ExpressCompanyID {
            get {
                return this.ExpressCompanyIDField;
            }
            set {
                if ((this.ExpressCompanyIDField.Equals(value) != true)) {
                    this.ExpressCompanyIDField = value;
                    this.RaisePropertyChanged("ExpressCompanyID");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ExpressCompanyName {
            get {
                return this.ExpressCompanyNameField;
            }
            set {
                if ((object.ReferenceEquals(this.ExpressCompanyNameField, value) != true)) {
                    this.ExpressCompanyNameField = value;
                    this.RaisePropertyChanged("ExpressCompanyName");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string FormCode {
            get {
                return this.FormCodeField;
            }
            set {
                if ((object.ReferenceEquals(this.FormCodeField, value) != true)) {
                    this.FormCodeField = value;
                    this.RaisePropertyChanged("FormCode");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string FromAddress {
            get {
                return this.FromAddressField;
            }
            set {
                if ((object.ReferenceEquals(this.FromAddressField, value) != true)) {
                    this.FromAddressField = value;
                    this.RaisePropertyChanged("FromAddress");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string FromArea {
            get {
                return this.FromAreaField;
            }
            set {
                if ((object.ReferenceEquals(this.FromAreaField, value) != true)) {
                    this.FromAreaField = value;
                    this.RaisePropertyChanged("FromArea");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string FromCity {
            get {
                return this.FromCityField;
            }
            set {
                if ((object.ReferenceEquals(this.FromCityField, value) != true)) {
                    this.FromCityField = value;
                    this.RaisePropertyChanged("FromCity");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string FromProvince {
            get {
                return this.FromProvinceField;
            }
            set {
                if ((object.ReferenceEquals(this.FromProvinceField, value) != true)) {
                    this.FromProvinceField = value;
                    this.RaisePropertyChanged("FromProvince");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string GoodsCategory {
            get {
                return this.GoodsCategoryField;
            }
            set {
                if ((object.ReferenceEquals(this.GoodsCategoryField, value) != true)) {
                    this.GoodsCategoryField = value;
                    this.RaisePropertyChanged("GoodsCategory");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string GoodsProperty {
            get {
                return this.GoodsPropertyField;
            }
            set {
                if ((object.ReferenceEquals(this.GoodsPropertyField, value) != true)) {
                    this.GoodsPropertyField = value;
                    this.RaisePropertyChanged("GoodsProperty");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string HouseCode {
            get {
                return this.HouseCodeField;
            }
            set {
                if ((object.ReferenceEquals(this.HouseCodeField, value) != true)) {
                    this.HouseCodeField = value;
                    this.RaisePropertyChanged("HouseCode");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int IncludeOrders {
            get {
                return this.IncludeOrdersField;
            }
            set {
                if ((this.IncludeOrdersField.Equals(value) != true)) {
                    this.IncludeOrdersField = value;
                    this.RaisePropertyChanged("IncludeOrders");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<bool> IsAutoAssign {
            get {
                return this.IsAutoAssignField;
            }
            set {
                if ((this.IsAutoAssignField.Equals(value) != true)) {
                    this.IsAutoAssignField = value;
                    this.RaisePropertyChanged("IsAutoAssign");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<bool> IsDelete {
            get {
                return this.IsDeleteField;
            }
            set {
                if ((this.IsDeleteField.Equals(value) != true)) {
                    this.IsDeleteField = value;
                    this.RaisePropertyChanged("IsDelete");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<bool> IsGisSuccess {
            get {
                return this.IsGisSuccessField;
            }
            set {
                if ((this.IsGisSuccessField.Equals(value) != true)) {
                    this.IsGisSuccessField = value;
                    this.RaisePropertyChanged("IsGisSuccess");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<bool> IsImported {
            get {
                return this.IsImportedField;
            }
            set {
                if ((this.IsImportedField.Equals(value) != true)) {
                    this.IsImportedField = value;
                    this.RaisePropertyChanged("IsImported");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<bool> IsSyn {
            get {
                return this.IsSynField;
            }
            set {
                if ((this.IsSynField.Equals(value) != true)) {
                    this.IsSynField = value;
                    this.RaisePropertyChanged("IsSyn");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string LineNumber {
            get {
                return this.LineNumberField;
            }
            set {
                if ((object.ReferenceEquals(this.LineNumberField, value) != true)) {
                    this.LineNumberField = value;
                    this.RaisePropertyChanged("LineNumber");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string LogisticProviderID {
            get {
                return this.LogisticProviderIDField;
            }
            set {
                if ((object.ReferenceEquals(this.LogisticProviderIDField, value) != true)) {
                    this.LogisticProviderIDField = value;
                    this.RaisePropertyChanged("LogisticProviderID");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<int> Marchartid {
            get {
                return this.MarchartidField;
            }
            set {
                if ((this.MarchartidField.Equals(value) != true)) {
                    this.MarchartidField = value;
                    this.RaisePropertyChanged("Marchartid");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string MobilePhone {
            get {
                return this.MobilePhoneField;
            }
            set {
                if ((object.ReferenceEquals(this.MobilePhoneField, value) != true)) {
                    this.MobilePhoneField = value;
                    this.RaisePropertyChanged("MobilePhone");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<decimal> NeedFund {
            get {
                return this.NeedFundField;
            }
            set {
                if ((this.NeedFundField.Equals(value) != true)) {
                    this.NeedFundField = value;
                    this.RaisePropertyChanged("NeedFund");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public Vancl.TMS.Schedule.Dps2TmsService.DpsOrdersForTMS.OrderForThirdPartyDetails[] OrderForThirdPartyDetailList {
            get {
                return this.OrderForThirdPartyDetailListField;
            }
            set {
                if ((object.ReferenceEquals(this.OrderForThirdPartyDetailListField, value) != true)) {
                    this.OrderForThirdPartyDetailListField = value;
                    this.RaisePropertyChanged("OrderForThirdPartyDetailList");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public long OrderForThirdPartyId {
            get {
                return this.OrderForThirdPartyIdField;
            }
            set {
                if ((this.OrderForThirdPartyIdField.Equals(value) != true)) {
                    this.OrderForThirdPartyIdField = value;
                    this.RaisePropertyChanged("OrderForThirdPartyId");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string OrderIndex {
            get {
                return this.OrderIndexField;
            }
            set {
                if ((object.ReferenceEquals(this.OrderIndexField, value) != true)) {
                    this.OrderIndexField = value;
                    this.RaisePropertyChanged("OrderIndex");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<decimal> OrderInfoVolume {
            get {
                return this.OrderInfoVolumeField;
            }
            set {
                if ((this.OrderInfoVolumeField.Equals(value) != true)) {
                    this.OrderInfoVolumeField = value;
                    this.RaisePropertyChanged("OrderInfoVolume");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<int> OrderType {
            get {
                return this.OrderTypeField;
            }
            set {
                if ((this.OrderTypeField.Equals(value) != true)) {
                    this.OrderTypeField = value;
                    this.RaisePropertyChanged("OrderType");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string OriginDepotNo {
            get {
                return this.OriginDepotNoField;
            }
            set {
                if ((object.ReferenceEquals(this.OriginDepotNoField, value) != true)) {
                    this.OriginDepotNoField = value;
                    this.RaisePropertyChanged("OriginDepotNo");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string PackageType {
            get {
                return this.PackageTypeField;
            }
            set {
                if ((object.ReferenceEquals(this.PackageTypeField, value) != true)) {
                    this.PackageTypeField = value;
                    this.RaisePropertyChanged("PackageType");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<decimal> PaidPrice {
            get {
                return this.PaidPriceField;
            }
            set {
                if ((this.PaidPriceField.Equals(value) != true)) {
                    this.PaidPriceField = value;
                    this.RaisePropertyChanged("PaidPrice");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<int> PaymentTypeID {
            get {
                return this.PaymentTypeIDField;
            }
            set {
                if ((this.PaymentTypeIDField.Equals(value) != true)) {
                    this.PaymentTypeIDField = value;
                    this.RaisePropertyChanged("PaymentTypeID");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string PerFormCode {
            get {
                return this.PerFormCodeField;
            }
            set {
                if ((object.ReferenceEquals(this.PerFormCodeField, value) != true)) {
                    this.PerFormCodeField = value;
                    this.RaisePropertyChanged("PerFormCode");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string PostalCode {
            get {
                return this.PostalCodeField;
            }
            set {
                if ((object.ReferenceEquals(this.PostalCodeField, value) != true)) {
                    this.PostalCodeField = value;
                    this.RaisePropertyChanged("PostalCode");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<decimal> Price {
            get {
                return this.PriceField;
            }
            set {
                if ((this.PriceField.Equals(value) != true)) {
                    this.PriceField = value;
                    this.RaisePropertyChanged("Price");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int ProjectExpress {
            get {
                return this.ProjectExpressField;
            }
            set {
                if ((this.ProjectExpressField.Equals(value) != true)) {
                    this.ProjectExpressField = value;
                    this.RaisePropertyChanged("ProjectExpress");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<decimal> Protectedprice {
            get {
                return this.ProtectedpriceField;
            }
            set {
                if ((this.ProtectedpriceField.Equals(value) != true)) {
                    this.ProtectedpriceField = value;
                    this.RaisePropertyChanged("Protectedprice");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Province {
            get {
                return this.ProvinceField;
            }
            set {
                if ((object.ReferenceEquals(this.ProvinceField, value) != true)) {
                    this.ProvinceField = value;
                    this.RaisePropertyChanged("Province");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ReceiveTel {
            get {
                return this.ReceiveTelField;
            }
            set {
                if ((object.ReferenceEquals(this.ReceiveTelField, value) != true)) {
                    this.ReceiveTelField = value;
                    this.RaisePropertyChanged("ReceiveTel");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<System.DateTime> ReceiveTime {
            get {
                return this.ReceiveTimeField;
            }
            set {
                if ((this.ReceiveTimeField.Equals(value) != true)) {
                    this.ReceiveTimeField = value;
                    this.RaisePropertyChanged("ReceiveTime");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Receiver {
            get {
                return this.ReceiverField;
            }
            set {
                if ((object.ReferenceEquals(this.ReceiverField, value) != true)) {
                    this.ReceiverField = value;
                    this.RaisePropertyChanged("Receiver");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string RelHouseCode {
            get {
                return this.RelHouseCodeField;
            }
            set {
                if ((object.ReferenceEquals(this.RelHouseCodeField, value) != true)) {
                    this.RelHouseCodeField = value;
                    this.RaisePropertyChanged("RelHouseCode");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ReplaceType {
            get {
                return this.ReplaceTypeField;
            }
            set {
                if ((object.ReferenceEquals(this.ReplaceTypeField, value) != true)) {
                    this.ReplaceTypeField = value;
                    this.RaisePropertyChanged("ReplaceType");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<decimal> ReturnSum {
            get {
                return this.ReturnSumField;
            }
            set {
                if ((this.ReturnSumField.Equals(value) != true)) {
                    this.ReturnSumField = value;
                    this.RaisePropertyChanged("ReturnSum");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string SendTimeType {
            get {
                return this.SendTimeTypeField;
            }
            set {
                if ((object.ReferenceEquals(this.SendTimeTypeField, value) != true)) {
                    this.SendTimeTypeField = value;
                    this.RaisePropertyChanged("SendTimeType");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<int> SortingCenterId {
            get {
                return this.SortingCenterIdField;
            }
            set {
                if ((this.SortingCenterIdField.Equals(value) != true)) {
                    this.SortingCenterIdField = value;
                    this.RaisePropertyChanged("SortingCenterId");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string SortingCenterName {
            get {
                return this.SortingCenterNameField;
            }
            set {
                if ((object.ReferenceEquals(this.SortingCenterNameField, value) != true)) {
                    this.SortingCenterNameField = value;
                    this.RaisePropertyChanged("SortingCenterName");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<int> Source {
            get {
                return this.SourceField;
            }
            set {
                if ((this.SourceField.Equals(value) != true)) {
                    this.SourceField = value;
                    this.RaisePropertyChanged("Source");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<int> Status {
            get {
                return this.StatusField;
            }
            set {
                if ((this.StatusField.Equals(value) != true)) {
                    this.StatusField = value;
                    this.RaisePropertyChanged("Status");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string SupplierName {
            get {
                return this.SupplierNameField;
            }
            set {
                if ((object.ReferenceEquals(this.SupplierNameField, value) != true)) {
                    this.SupplierNameField = value;
                    this.RaisePropertyChanged("SupplierName");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool SupportDeliverCode {
            get {
                return this.SupportDeliverCodeField;
            }
            set {
                if ((this.SupportDeliverCodeField.Equals(value) != true)) {
                    this.SupportDeliverCodeField = value;
                    this.RaisePropertyChanged("SupportDeliverCode");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int TimeType {
            get {
                return this.TimeTypeField;
            }
            set {
                if ((this.TimeTypeField.Equals(value) != true)) {
                    this.TimeTypeField = value;
                    this.RaisePropertyChanged("TimeType");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<decimal> TransferPrice {
            get {
                return this.TransferPriceField;
            }
            set {
                if ((this.TransferPriceField.Equals(value) != true)) {
                    this.TransferPriceField = value;
                    this.RaisePropertyChanged("TransferPrice");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool UnGisAssign {
            get {
                return this.UnGisAssignField;
            }
            set {
                if ((this.UnGisAssignField.Equals(value) != true)) {
                    this.UnGisAssignField = value;
                    this.RaisePropertyChanged("UnGisAssign");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<int> UpdateBy {
            get {
                return this.UpdateByField;
            }
            set {
                if ((this.UpdateByField.Equals(value) != true)) {
                    this.UpdateByField = value;
                    this.RaisePropertyChanged("UpdateBy");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<int> UpdateStationId {
            get {
                return this.UpdateStationIdField;
            }
            set {
                if ((this.UpdateStationIdField.Equals(value) != true)) {
                    this.UpdateStationIdField = value;
                    this.RaisePropertyChanged("UpdateStationId");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<System.DateTime> UpdateTime {
            get {
                return this.UpdateTimeField;
            }
            set {
                if ((this.UpdateTimeField.Equals(value) != true)) {
                    this.UpdateTimeField = value;
                    this.RaisePropertyChanged("UpdateTime");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string UserName {
            get {
                return this.UserNameField;
            }
            set {
                if ((object.ReferenceEquals(this.UserNameField, value) != true)) {
                    this.UserNameField = value;
                    this.RaisePropertyChanged("UserName");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string WarehouseName {
            get {
                return this.WarehouseNameField;
            }
            set {
                if ((object.ReferenceEquals(this.WarehouseNameField, value) != true)) {
                    this.WarehouseNameField = value;
                    this.RaisePropertyChanged("WarehouseName");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string WaybillBoxModel {
            get {
                return this.WaybillBoxModelField;
            }
            set {
                if ((object.ReferenceEquals(this.WaybillBoxModelField, value) != true)) {
                    this.WaybillBoxModelField = value;
                    this.RaisePropertyChanged("WaybillBoxModel");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<long> WaybillNo {
            get {
                return this.WaybillNoField;
            }
            set {
                if ((this.WaybillNoField.Equals(value) != true)) {
                    this.WaybillNoField = value;
                    this.RaisePropertyChanged("WaybillNo");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<decimal> Weight {
            get {
                return this.WeightField;
            }
            set {
                if ((this.WeightField.Equals(value) != true)) {
                    this.WeightField = value;
                    this.RaisePropertyChanged("Weight");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="OrderForThirdPartyDetails", Namespace="http://schemas.datacontract.org/2004/07/Cloud.DPS.Model.OrderForThirdParty")]
    [System.SerializableAttribute()]
    public partial class OrderForThirdPartyDetails : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        private string _ReasonField;
        
        private string _ReasonIDField;
        
        private System.Nullable<int> _createbyField;
        
        private System.Nullable<int> _createstationidField;
        
        private System.Nullable<System.DateTime> _createtimeField;
        
        private string _formcodeField;
        
        private System.Nullable<bool> _isdeleteField;
        
        private System.Nullable<bool> _issynField;
        
        private System.Nullable<decimal> _orderamountField;
        
        private long _orderforthirdpartydetailsidField;
        
        private long _orderforthirdpartyidField;
        
        private string _productcodeField;
        
        private string _productnameField;
        
        private System.Nullable<decimal> _sellpriceField;
        
        private string _sizeField;
        
        private string _unitField;
        
        private System.Nullable<int> _updatebyField;
        
        private System.Nullable<int> _updatestationidField;
        
        private System.Nullable<System.DateTime> _updatetimeField;
        
        private string Remarkk__BackingFieldField;
        
        private System.Nullable<decimal> Volumnk__BackingFieldField;
        
        private System.Nullable<decimal> Weightk__BackingFieldField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public string _Reason {
            get {
                return this._ReasonField;
            }
            set {
                if ((object.ReferenceEquals(this._ReasonField, value) != true)) {
                    this._ReasonField = value;
                    this.RaisePropertyChanged("_Reason");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public string _ReasonID {
            get {
                return this._ReasonIDField;
            }
            set {
                if ((object.ReferenceEquals(this._ReasonIDField, value) != true)) {
                    this._ReasonIDField = value;
                    this.RaisePropertyChanged("_ReasonID");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public System.Nullable<int> _createby {
            get {
                return this._createbyField;
            }
            set {
                if ((this._createbyField.Equals(value) != true)) {
                    this._createbyField = value;
                    this.RaisePropertyChanged("_createby");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public System.Nullable<int> _createstationid {
            get {
                return this._createstationidField;
            }
            set {
                if ((this._createstationidField.Equals(value) != true)) {
                    this._createstationidField = value;
                    this.RaisePropertyChanged("_createstationid");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public System.Nullable<System.DateTime> _createtime {
            get {
                return this._createtimeField;
            }
            set {
                if ((this._createtimeField.Equals(value) != true)) {
                    this._createtimeField = value;
                    this.RaisePropertyChanged("_createtime");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public string _formcode {
            get {
                return this._formcodeField;
            }
            set {
                if ((object.ReferenceEquals(this._formcodeField, value) != true)) {
                    this._formcodeField = value;
                    this.RaisePropertyChanged("_formcode");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public System.Nullable<bool> _isdelete {
            get {
                return this._isdeleteField;
            }
            set {
                if ((this._isdeleteField.Equals(value) != true)) {
                    this._isdeleteField = value;
                    this.RaisePropertyChanged("_isdelete");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public System.Nullable<bool> _issyn {
            get {
                return this._issynField;
            }
            set {
                if ((this._issynField.Equals(value) != true)) {
                    this._issynField = value;
                    this.RaisePropertyChanged("_issyn");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public System.Nullable<decimal> _orderamount {
            get {
                return this._orderamountField;
            }
            set {
                if ((this._orderamountField.Equals(value) != true)) {
                    this._orderamountField = value;
                    this.RaisePropertyChanged("_orderamount");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public long _orderforthirdpartydetailsid {
            get {
                return this._orderforthirdpartydetailsidField;
            }
            set {
                if ((this._orderforthirdpartydetailsidField.Equals(value) != true)) {
                    this._orderforthirdpartydetailsidField = value;
                    this.RaisePropertyChanged("_orderforthirdpartydetailsid");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public long _orderforthirdpartyid {
            get {
                return this._orderforthirdpartyidField;
            }
            set {
                if ((this._orderforthirdpartyidField.Equals(value) != true)) {
                    this._orderforthirdpartyidField = value;
                    this.RaisePropertyChanged("_orderforthirdpartyid");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public string _productcode {
            get {
                return this._productcodeField;
            }
            set {
                if ((object.ReferenceEquals(this._productcodeField, value) != true)) {
                    this._productcodeField = value;
                    this.RaisePropertyChanged("_productcode");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public string _productname {
            get {
                return this._productnameField;
            }
            set {
                if ((object.ReferenceEquals(this._productnameField, value) != true)) {
                    this._productnameField = value;
                    this.RaisePropertyChanged("_productname");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public System.Nullable<decimal> _sellprice {
            get {
                return this._sellpriceField;
            }
            set {
                if ((this._sellpriceField.Equals(value) != true)) {
                    this._sellpriceField = value;
                    this.RaisePropertyChanged("_sellprice");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public string _size {
            get {
                return this._sizeField;
            }
            set {
                if ((object.ReferenceEquals(this._sizeField, value) != true)) {
                    this._sizeField = value;
                    this.RaisePropertyChanged("_size");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public string _unit {
            get {
                return this._unitField;
            }
            set {
                if ((object.ReferenceEquals(this._unitField, value) != true)) {
                    this._unitField = value;
                    this.RaisePropertyChanged("_unit");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public System.Nullable<int> _updateby {
            get {
                return this._updatebyField;
            }
            set {
                if ((this._updatebyField.Equals(value) != true)) {
                    this._updatebyField = value;
                    this.RaisePropertyChanged("_updateby");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public System.Nullable<int> _updatestationid {
            get {
                return this._updatestationidField;
            }
            set {
                if ((this._updatestationidField.Equals(value) != true)) {
                    this._updatestationidField = value;
                    this.RaisePropertyChanged("_updatestationid");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public System.Nullable<System.DateTime> _updatetime {
            get {
                return this._updatetimeField;
            }
            set {
                if ((this._updatetimeField.Equals(value) != true)) {
                    this._updatetimeField = value;
                    this.RaisePropertyChanged("_updatetime");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Name="<Remark>k__BackingField", IsRequired=true)]
        public string Remarkk__BackingField {
            get {
                return this.Remarkk__BackingFieldField;
            }
            set {
                if ((object.ReferenceEquals(this.Remarkk__BackingFieldField, value) != true)) {
                    this.Remarkk__BackingFieldField = value;
                    this.RaisePropertyChanged("Remarkk__BackingField");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Name="<Volumn>k__BackingField", IsRequired=true)]
        public System.Nullable<decimal> Volumnk__BackingField {
            get {
                return this.Volumnk__BackingFieldField;
            }
            set {
                if ((this.Volumnk__BackingFieldField.Equals(value) != true)) {
                    this.Volumnk__BackingFieldField = value;
                    this.RaisePropertyChanged("Volumnk__BackingField");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Name="<Weight>k__BackingField", IsRequired=true)]
        public System.Nullable<decimal> Weightk__BackingField {
            get {
                return this.Weightk__BackingFieldField;
            }
            set {
                if ((this.Weightk__BackingFieldField.Equals(value) != true)) {
                    this.Weightk__BackingFieldField = value;
                    this.RaisePropertyChanged("Weightk__BackingField");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="DpsOrdersForTMS.IOrdersForTms")]
    public interface IOrdersForTms {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IOrdersForTms/GetDpsDataForTMS", ReplyAction="http://tempuri.org/IOrdersForTms/GetDpsDataForTMSResponse")]
        Vancl.TMS.Schedule.Dps2TmsService.DpsOrdersForTMS.OrderForThirdParty[] GetDpsDataForTMS(int top);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IOrdersForTms/UpdateGetStatus", ReplyAction="http://tempuri.org/IOrdersForTms/UpdateGetStatusResponse")]
        bool UpdateGetStatus(long[] ids);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IOrdersForTmsChannel : Vancl.TMS.Schedule.Dps2TmsService.DpsOrdersForTMS.IOrdersForTms, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class OrdersForTmsClient : System.ServiceModel.ClientBase<Vancl.TMS.Schedule.Dps2TmsService.DpsOrdersForTMS.IOrdersForTms>, Vancl.TMS.Schedule.Dps2TmsService.DpsOrdersForTMS.IOrdersForTms {
        
        public OrdersForTmsClient() {
        }
        
        public OrdersForTmsClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public OrdersForTmsClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public OrdersForTmsClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public OrdersForTmsClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public Vancl.TMS.Schedule.Dps2TmsService.DpsOrdersForTMS.OrderForThirdParty[] GetDpsDataForTMS(int top) {
            return base.Channel.GetDpsDataForTMS(top);
        }
        
        public bool UpdateGetStatus(long[] ids) {
            return base.Channel.UpdateGetStatus(ids);
        }
    }
}
