//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.269
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Vancl.TMS.BLL.TransPointService {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="TransPointService.ITmsDataService")]
    public interface ITmsDataService {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ITmsDataService/FromDeliverCenter", ReplyAction="http://tempuri.org/ITmsDataService/FromDeliverCenterResponse")]
        System.Collections.Generic.Dictionary<int, string> FromDeliverCenter();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ITmsDataService/ToDeliverCenter", ReplyAction="http://tempuri.org/ITmsDataService/ToDeliverCenterResponse")]
        System.Collections.Generic.Dictionary<int, string> ToDeliverCenter(int fromDeliverCenter);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ITmsDataService/GetDeliverCenterByStation", ReplyAction="http://tempuri.org/ITmsDataService/GetDeliverCenterByStationResponse")]
        int GetDeliverCenterByStation(int stationId);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ITmsDataService/IsNeedTmsTransfer", ReplyAction="http://tempuri.org/ITmsDataService/IsNeedTmsTransferResponse")]
        int IsNeedTmsTransfer(int fromId, ref int toId);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface ITmsDataServiceChannel : Vancl.TMS.BLL.TransPointService.ITmsDataService, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class TmsDataServiceClient : System.ServiceModel.ClientBase<Vancl.TMS.BLL.TransPointService.ITmsDataService>, Vancl.TMS.BLL.TransPointService.ITmsDataService {
        
        public TmsDataServiceClient() {
        }
        
        public TmsDataServiceClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public TmsDataServiceClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public TmsDataServiceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public TmsDataServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public System.Collections.Generic.Dictionary<int, string> FromDeliverCenter() {
            return base.Channel.FromDeliverCenter();
        }
        
        public System.Collections.Generic.Dictionary<int, string> ToDeliverCenter(int fromDeliverCenter) {
            return base.Channel.ToDeliverCenter(fromDeliverCenter);
        }
        
        public int GetDeliverCenterByStation(int stationId) {
            return base.Channel.GetDeliverCenterByStation(stationId);
        }
        
        public int IsNeedTmsTransfer(int fromId, ref int toId) {
            return base.Channel.IsNeedTmsTransfer(fromId, ref toId);
        }
    }
}
