//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.17929
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Vancl.TMS.BLL.WaybillLifeCycleService {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="WaybillLifeCycleDto", Namespace="http://schemas.datacontract.org/2004/07/Cloud.DPS.Model.DTOModel.WaybillLifeCycle" +
        "")]
    [System.SerializableAttribute()]
    public partial class WaybillLifeCycleDto : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int CurNodeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<int> DeliverStationIDField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string DistributionCodeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string NoteField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<System.DateTime> OpDateField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int OpDeptIDField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int OpManIDField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string OperationField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int StatusField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int SubStatusField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ToDistributionCodeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<int> ToExpressCompanyIDField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private long WaybillNoField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int CurNode {
            get {
                return this.CurNodeField;
            }
            set {
                if ((this.CurNodeField.Equals(value) != true)) {
                    this.CurNodeField = value;
                    this.RaisePropertyChanged("CurNode");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<int> DeliverStationID {
            get {
                return this.DeliverStationIDField;
            }
            set {
                if ((this.DeliverStationIDField.Equals(value) != true)) {
                    this.DeliverStationIDField = value;
                    this.RaisePropertyChanged("DeliverStationID");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string DistributionCode {
            get {
                return this.DistributionCodeField;
            }
            set {
                if ((object.ReferenceEquals(this.DistributionCodeField, value) != true)) {
                    this.DistributionCodeField = value;
                    this.RaisePropertyChanged("DistributionCode");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Note {
            get {
                return this.NoteField;
            }
            set {
                if ((object.ReferenceEquals(this.NoteField, value) != true)) {
                    this.NoteField = value;
                    this.RaisePropertyChanged("Note");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<System.DateTime> OpDate {
            get {
                return this.OpDateField;
            }
            set {
                if ((this.OpDateField.Equals(value) != true)) {
                    this.OpDateField = value;
                    this.RaisePropertyChanged("OpDate");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int OpDeptID {
            get {
                return this.OpDeptIDField;
            }
            set {
                if ((this.OpDeptIDField.Equals(value) != true)) {
                    this.OpDeptIDField = value;
                    this.RaisePropertyChanged("OpDeptID");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int OpManID {
            get {
                return this.OpManIDField;
            }
            set {
                if ((this.OpManIDField.Equals(value) != true)) {
                    this.OpManIDField = value;
                    this.RaisePropertyChanged("OpManID");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Operation {
            get {
                return this.OperationField;
            }
            set {
                if ((object.ReferenceEquals(this.OperationField, value) != true)) {
                    this.OperationField = value;
                    this.RaisePropertyChanged("Operation");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Status {
            get {
                return this.StatusField;
            }
            set {
                if ((this.StatusField.Equals(value) != true)) {
                    this.StatusField = value;
                    this.RaisePropertyChanged("Status");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int SubStatus {
            get {
                return this.SubStatusField;
            }
            set {
                if ((this.SubStatusField.Equals(value) != true)) {
                    this.SubStatusField = value;
                    this.RaisePropertyChanged("SubStatus");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ToDistributionCode {
            get {
                return this.ToDistributionCodeField;
            }
            set {
                if ((object.ReferenceEquals(this.ToDistributionCodeField, value) != true)) {
                    this.ToDistributionCodeField = value;
                    this.RaisePropertyChanged("ToDistributionCode");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<int> ToExpressCompanyID {
            get {
                return this.ToExpressCompanyIDField;
            }
            set {
                if ((this.ToExpressCompanyIDField.Equals(value) != true)) {
                    this.ToExpressCompanyIDField = value;
                    this.RaisePropertyChanged("ToExpressCompanyID");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public long WaybillNo {
            get {
                return this.WaybillNoField;
            }
            set {
                if ((this.WaybillNoField.Equals(value) != true)) {
                    this.WaybillNoField = value;
                    this.RaisePropertyChanged("WaybillNo");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="InBound", Namespace="http://schemas.datacontract.org/2004/07/Cloud.DPS.Model.WaybillLifeCycle")]
    [System.SerializableAttribute()]
    public partial class InBound : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private bool firstField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.DateTime opdateField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int opmanIdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int sortingCenterIdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int statusField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private long waybillnoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private decimal weightField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool first {
            get {
                return this.firstField;
            }
            set {
                if ((this.firstField.Equals(value) != true)) {
                    this.firstField = value;
                    this.RaisePropertyChanged("first");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime opdate {
            get {
                return this.opdateField;
            }
            set {
                if ((this.opdateField.Equals(value) != true)) {
                    this.opdateField = value;
                    this.RaisePropertyChanged("opdate");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int opmanId {
            get {
                return this.opmanIdField;
            }
            set {
                if ((this.opmanIdField.Equals(value) != true)) {
                    this.opmanIdField = value;
                    this.RaisePropertyChanged("opmanId");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int sortingCenterId {
            get {
                return this.sortingCenterIdField;
            }
            set {
                if ((this.sortingCenterIdField.Equals(value) != true)) {
                    this.sortingCenterIdField = value;
                    this.RaisePropertyChanged("sortingCenterId");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int status {
            get {
                return this.statusField;
            }
            set {
                if ((this.statusField.Equals(value) != true)) {
                    this.statusField = value;
                    this.RaisePropertyChanged("status");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public long waybillno {
            get {
                return this.waybillnoField;
            }
            set {
                if ((this.waybillnoField.Equals(value) != true)) {
                    this.waybillnoField = value;
                    this.RaisePropertyChanged("waybillno");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public decimal weight {
            get {
                return this.weightField;
            }
            set {
                if ((this.weightField.Equals(value) != true)) {
                    this.weightField = value;
                    this.RaisePropertyChanged("weight");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="BackStation", Namespace="http://schemas.datacontract.org/2004/07/Cloud.DPS.Model.WaybillLifeCycle")]
    [System.SerializableAttribute()]
    public partial class BackStation : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string AcceptTypeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<int> CreatByField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<int> CreatStationField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<System.DateTime> CreatTimeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<int> DeliverManField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<int> DeliverStationIdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ReasonField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string SignCustomerField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string SignStatusField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<int> SignTypeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private long WaybillNOField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string AcceptType {
            get {
                return this.AcceptTypeField;
            }
            set {
                if ((object.ReferenceEquals(this.AcceptTypeField, value) != true)) {
                    this.AcceptTypeField = value;
                    this.RaisePropertyChanged("AcceptType");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<int> CreatBy {
            get {
                return this.CreatByField;
            }
            set {
                if ((this.CreatByField.Equals(value) != true)) {
                    this.CreatByField = value;
                    this.RaisePropertyChanged("CreatBy");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<int> CreatStation {
            get {
                return this.CreatStationField;
            }
            set {
                if ((this.CreatStationField.Equals(value) != true)) {
                    this.CreatStationField = value;
                    this.RaisePropertyChanged("CreatStation");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<System.DateTime> CreatTime {
            get {
                return this.CreatTimeField;
            }
            set {
                if ((this.CreatTimeField.Equals(value) != true)) {
                    this.CreatTimeField = value;
                    this.RaisePropertyChanged("CreatTime");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<int> DeliverMan {
            get {
                return this.DeliverManField;
            }
            set {
                if ((this.DeliverManField.Equals(value) != true)) {
                    this.DeliverManField = value;
                    this.RaisePropertyChanged("DeliverMan");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<int> DeliverStationId {
            get {
                return this.DeliverStationIdField;
            }
            set {
                if ((this.DeliverStationIdField.Equals(value) != true)) {
                    this.DeliverStationIdField = value;
                    this.RaisePropertyChanged("DeliverStationId");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Reason {
            get {
                return this.ReasonField;
            }
            set {
                if ((object.ReferenceEquals(this.ReasonField, value) != true)) {
                    this.ReasonField = value;
                    this.RaisePropertyChanged("Reason");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string SignCustomer {
            get {
                return this.SignCustomerField;
            }
            set {
                if ((object.ReferenceEquals(this.SignCustomerField, value) != true)) {
                    this.SignCustomerField = value;
                    this.RaisePropertyChanged("SignCustomer");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string SignStatus {
            get {
                return this.SignStatusField;
            }
            set {
                if ((object.ReferenceEquals(this.SignStatusField, value) != true)) {
                    this.SignStatusField = value;
                    this.RaisePropertyChanged("SignStatus");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<int> SignType {
            get {
                return this.SignTypeField;
            }
            set {
                if ((this.SignTypeField.Equals(value) != true)) {
                    this.SignTypeField = value;
                    this.RaisePropertyChanged("SignType");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public long WaybillNO {
            get {
                return this.WaybillNOField;
            }
            set {
                if ((this.WaybillNOField.Equals(value) != true)) {
                    this.WaybillNOField = value;
                    this.RaisePropertyChanged("WaybillNO");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="WaybillDeal", Namespace="http://schemas.datacontract.org/2004/07/Cloud.DPS.Model.WaybillLifeCycle")]
    [System.SerializableAttribute()]
    public partial class WaybillDeal : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<int> CreatByField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<int> CreatStationField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<System.DateTime> CreatTimeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<int> DealManField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<int> DealStationField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<System.DateTime> DealTimeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private long WaybillNOField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<int> CreatBy {
            get {
                return this.CreatByField;
            }
            set {
                if ((this.CreatByField.Equals(value) != true)) {
                    this.CreatByField = value;
                    this.RaisePropertyChanged("CreatBy");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<int> CreatStation {
            get {
                return this.CreatStationField;
            }
            set {
                if ((this.CreatStationField.Equals(value) != true)) {
                    this.CreatStationField = value;
                    this.RaisePropertyChanged("CreatStation");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<System.DateTime> CreatTime {
            get {
                return this.CreatTimeField;
            }
            set {
                if ((this.CreatTimeField.Equals(value) != true)) {
                    this.CreatTimeField = value;
                    this.RaisePropertyChanged("CreatTime");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<int> DealMan {
            get {
                return this.DealManField;
            }
            set {
                if ((this.DealManField.Equals(value) != true)) {
                    this.DealManField = value;
                    this.RaisePropertyChanged("DealMan");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<int> DealStation {
            get {
                return this.DealStationField;
            }
            set {
                if ((this.DealStationField.Equals(value) != true)) {
                    this.DealStationField = value;
                    this.RaisePropertyChanged("DealStation");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<System.DateTime> DealTime {
            get {
                return this.DealTimeField;
            }
            set {
                if ((this.DealTimeField.Equals(value) != true)) {
                    this.DealTimeField = value;
                    this.RaisePropertyChanged("DealTime");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public long WaybillNO {
            get {
                return this.WaybillNOField;
            }
            set {
                if ((this.WaybillNOField.Equals(value) != true)) {
                    this.WaybillNOField = value;
                    this.RaisePropertyChanged("WaybillNO");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="PickUp", Namespace="http://schemas.datacontract.org/2004/07/Cloud.DPS.Model.WaybillLifeCycle")]
    [System.SerializableAttribute()]
    public partial class PickUp : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string AssignDistributionCodeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int AssignStatusField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.DateTime OpDateField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int SortingCenterIdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int StationIdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int StatusField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private long WaybillnoField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string AssignDistributionCode {
            get {
                return this.AssignDistributionCodeField;
            }
            set {
                if ((object.ReferenceEquals(this.AssignDistributionCodeField, value) != true)) {
                    this.AssignDistributionCodeField = value;
                    this.RaisePropertyChanged("AssignDistributionCode");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int AssignStatus {
            get {
                return this.AssignStatusField;
            }
            set {
                if ((this.AssignStatusField.Equals(value) != true)) {
                    this.AssignStatusField = value;
                    this.RaisePropertyChanged("AssignStatus");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime OpDate {
            get {
                return this.OpDateField;
            }
            set {
                if ((this.OpDateField.Equals(value) != true)) {
                    this.OpDateField = value;
                    this.RaisePropertyChanged("OpDate");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int SortingCenterId {
            get {
                return this.SortingCenterIdField;
            }
            set {
                if ((this.SortingCenterIdField.Equals(value) != true)) {
                    this.SortingCenterIdField = value;
                    this.RaisePropertyChanged("SortingCenterId");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int StationId {
            get {
                return this.StationIdField;
            }
            set {
                if ((this.StationIdField.Equals(value) != true)) {
                    this.StationIdField = value;
                    this.RaisePropertyChanged("StationId");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Status {
            get {
                return this.StatusField;
            }
            set {
                if ((this.StatusField.Equals(value) != true)) {
                    this.StatusField = value;
                    this.RaisePropertyChanged("Status");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public long Waybillno {
            get {
                return this.WaybillnoField;
            }
            set {
                if ((this.WaybillnoField.Equals(value) != true)) {
                    this.WaybillnoField = value;
                    this.RaisePropertyChanged("Waybillno");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="ExpressModel", Namespace="http://schemas.datacontract.org/2004/07/Cloud.DPS.Model.WaybillLifeCycle")]
    [System.SerializableAttribute()]
    public partial class ExpressModel : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string CommentField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<System.DateTime> ComplementTimeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<int> CreateByField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<int> CreateStationIdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<System.DateTime> CreateTimeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string CustomOrderField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<decimal> DeductNotesField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<decimal> DeliveryAcceptAmountField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string DeliveryAcceptTypeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<int> DeliveryFeeTypeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<int> DeliveryStationIdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string DistributionCodeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<decimal> FactorageField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<int> FetchEmployeeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<decimal> FinancialWeightField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<decimal> GoodsHighField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<decimal> GoodsLongField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<int> GoodsNumField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<decimal> GoodsPaymentField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string GoodsTypeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<decimal> GoodsWeightField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<decimal> GoodsWideField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<int> IntoStationIdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<System.DateTime> IntoStationTimeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<bool> IsComplementField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<bool> IsDeleteField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<bool> IsSynField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int LocalOrderField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<int> MonthlyMerchantIdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<System.DateTime> OutStationTimeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int ProjectExpressField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<decimal> ProtectFeeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<decimal> ProtectPriceField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ReceiveAddressField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ReceiveAreaField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ReceiveCityField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ReceiveDepartmentField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ReceiveNameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ReceivePhoneField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ReceivePostCodeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ReceiveProvinceField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ReceiveTelephoneField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string SendAddressField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string SendAreaField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string SendCityField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string SendDepartmentField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string SendNameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string SendPhoneField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string SendPostCodeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string SendProvinceField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<int> SendSortCenterIDField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string SendTelephoneField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<int> StatusField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<int> UpdateByField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<int> UpdateStationIdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<System.DateTime> UpdateTimeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private long WaybillNoField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Comment {
            get {
                return this.CommentField;
            }
            set {
                if ((object.ReferenceEquals(this.CommentField, value) != true)) {
                    this.CommentField = value;
                    this.RaisePropertyChanged("Comment");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<System.DateTime> ComplementTime {
            get {
                return this.ComplementTimeField;
            }
            set {
                if ((this.ComplementTimeField.Equals(value) != true)) {
                    this.ComplementTimeField = value;
                    this.RaisePropertyChanged("ComplementTime");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<int> CreateBy {
            get {
                return this.CreateByField;
            }
            set {
                if ((this.CreateByField.Equals(value) != true)) {
                    this.CreateByField = value;
                    this.RaisePropertyChanged("CreateBy");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<int> CreateStationId {
            get {
                return this.CreateStationIdField;
            }
            set {
                if ((this.CreateStationIdField.Equals(value) != true)) {
                    this.CreateStationIdField = value;
                    this.RaisePropertyChanged("CreateStationId");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<System.DateTime> CreateTime {
            get {
                return this.CreateTimeField;
            }
            set {
                if ((this.CreateTimeField.Equals(value) != true)) {
                    this.CreateTimeField = value;
                    this.RaisePropertyChanged("CreateTime");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string CustomOrder {
            get {
                return this.CustomOrderField;
            }
            set {
                if ((object.ReferenceEquals(this.CustomOrderField, value) != true)) {
                    this.CustomOrderField = value;
                    this.RaisePropertyChanged("CustomOrder");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<decimal> DeductNotes {
            get {
                return this.DeductNotesField;
            }
            set {
                if ((this.DeductNotesField.Equals(value) != true)) {
                    this.DeductNotesField = value;
                    this.RaisePropertyChanged("DeductNotes");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<decimal> DeliveryAcceptAmount {
            get {
                return this.DeliveryAcceptAmountField;
            }
            set {
                if ((this.DeliveryAcceptAmountField.Equals(value) != true)) {
                    this.DeliveryAcceptAmountField = value;
                    this.RaisePropertyChanged("DeliveryAcceptAmount");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string DeliveryAcceptType {
            get {
                return this.DeliveryAcceptTypeField;
            }
            set {
                if ((object.ReferenceEquals(this.DeliveryAcceptTypeField, value) != true)) {
                    this.DeliveryAcceptTypeField = value;
                    this.RaisePropertyChanged("DeliveryAcceptType");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<int> DeliveryFeeType {
            get {
                return this.DeliveryFeeTypeField;
            }
            set {
                if ((this.DeliveryFeeTypeField.Equals(value) != true)) {
                    this.DeliveryFeeTypeField = value;
                    this.RaisePropertyChanged("DeliveryFeeType");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<int> DeliveryStationId {
            get {
                return this.DeliveryStationIdField;
            }
            set {
                if ((this.DeliveryStationIdField.Equals(value) != true)) {
                    this.DeliveryStationIdField = value;
                    this.RaisePropertyChanged("DeliveryStationId");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string DistributionCode {
            get {
                return this.DistributionCodeField;
            }
            set {
                if ((object.ReferenceEquals(this.DistributionCodeField, value) != true)) {
                    this.DistributionCodeField = value;
                    this.RaisePropertyChanged("DistributionCode");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<decimal> Factorage {
            get {
                return this.FactorageField;
            }
            set {
                if ((this.FactorageField.Equals(value) != true)) {
                    this.FactorageField = value;
                    this.RaisePropertyChanged("Factorage");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<int> FetchEmployee {
            get {
                return this.FetchEmployeeField;
            }
            set {
                if ((this.FetchEmployeeField.Equals(value) != true)) {
                    this.FetchEmployeeField = value;
                    this.RaisePropertyChanged("FetchEmployee");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<decimal> FinancialWeight {
            get {
                return this.FinancialWeightField;
            }
            set {
                if ((this.FinancialWeightField.Equals(value) != true)) {
                    this.FinancialWeightField = value;
                    this.RaisePropertyChanged("FinancialWeight");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<decimal> GoodsHigh {
            get {
                return this.GoodsHighField;
            }
            set {
                if ((this.GoodsHighField.Equals(value) != true)) {
                    this.GoodsHighField = value;
                    this.RaisePropertyChanged("GoodsHigh");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<decimal> GoodsLong {
            get {
                return this.GoodsLongField;
            }
            set {
                if ((this.GoodsLongField.Equals(value) != true)) {
                    this.GoodsLongField = value;
                    this.RaisePropertyChanged("GoodsLong");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<int> GoodsNum {
            get {
                return this.GoodsNumField;
            }
            set {
                if ((this.GoodsNumField.Equals(value) != true)) {
                    this.GoodsNumField = value;
                    this.RaisePropertyChanged("GoodsNum");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<decimal> GoodsPayment {
            get {
                return this.GoodsPaymentField;
            }
            set {
                if ((this.GoodsPaymentField.Equals(value) != true)) {
                    this.GoodsPaymentField = value;
                    this.RaisePropertyChanged("GoodsPayment");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string GoodsType {
            get {
                return this.GoodsTypeField;
            }
            set {
                if ((object.ReferenceEquals(this.GoodsTypeField, value) != true)) {
                    this.GoodsTypeField = value;
                    this.RaisePropertyChanged("GoodsType");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<decimal> GoodsWeight {
            get {
                return this.GoodsWeightField;
            }
            set {
                if ((this.GoodsWeightField.Equals(value) != true)) {
                    this.GoodsWeightField = value;
                    this.RaisePropertyChanged("GoodsWeight");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<decimal> GoodsWide {
            get {
                return this.GoodsWideField;
            }
            set {
                if ((this.GoodsWideField.Equals(value) != true)) {
                    this.GoodsWideField = value;
                    this.RaisePropertyChanged("GoodsWide");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<int> IntoStationId {
            get {
                return this.IntoStationIdField;
            }
            set {
                if ((this.IntoStationIdField.Equals(value) != true)) {
                    this.IntoStationIdField = value;
                    this.RaisePropertyChanged("IntoStationId");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<System.DateTime> IntoStationTime {
            get {
                return this.IntoStationTimeField;
            }
            set {
                if ((this.IntoStationTimeField.Equals(value) != true)) {
                    this.IntoStationTimeField = value;
                    this.RaisePropertyChanged("IntoStationTime");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<bool> IsComplement {
            get {
                return this.IsComplementField;
            }
            set {
                if ((this.IsComplementField.Equals(value) != true)) {
                    this.IsComplementField = value;
                    this.RaisePropertyChanged("IsComplement");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<bool> IsDelete {
            get {
                return this.IsDeleteField;
            }
            set {
                if ((this.IsDeleteField.Equals(value) != true)) {
                    this.IsDeleteField = value;
                    this.RaisePropertyChanged("IsDelete");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<bool> IsSyn {
            get {
                return this.IsSynField;
            }
            set {
                if ((this.IsSynField.Equals(value) != true)) {
                    this.IsSynField = value;
                    this.RaisePropertyChanged("IsSyn");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int LocalOrder {
            get {
                return this.LocalOrderField;
            }
            set {
                if ((this.LocalOrderField.Equals(value) != true)) {
                    this.LocalOrderField = value;
                    this.RaisePropertyChanged("LocalOrder");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<int> MonthlyMerchantId {
            get {
                return this.MonthlyMerchantIdField;
            }
            set {
                if ((this.MonthlyMerchantIdField.Equals(value) != true)) {
                    this.MonthlyMerchantIdField = value;
                    this.RaisePropertyChanged("MonthlyMerchantId");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<System.DateTime> OutStationTime {
            get {
                return this.OutStationTimeField;
            }
            set {
                if ((this.OutStationTimeField.Equals(value) != true)) {
                    this.OutStationTimeField = value;
                    this.RaisePropertyChanged("OutStationTime");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int ProjectExpress {
            get {
                return this.ProjectExpressField;
            }
            set {
                if ((this.ProjectExpressField.Equals(value) != true)) {
                    this.ProjectExpressField = value;
                    this.RaisePropertyChanged("ProjectExpress");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<decimal> ProtectFee {
            get {
                return this.ProtectFeeField;
            }
            set {
                if ((this.ProtectFeeField.Equals(value) != true)) {
                    this.ProtectFeeField = value;
                    this.RaisePropertyChanged("ProtectFee");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<decimal> ProtectPrice {
            get {
                return this.ProtectPriceField;
            }
            set {
                if ((this.ProtectPriceField.Equals(value) != true)) {
                    this.ProtectPriceField = value;
                    this.RaisePropertyChanged("ProtectPrice");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ReceiveAddress {
            get {
                return this.ReceiveAddressField;
            }
            set {
                if ((object.ReferenceEquals(this.ReceiveAddressField, value) != true)) {
                    this.ReceiveAddressField = value;
                    this.RaisePropertyChanged("ReceiveAddress");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ReceiveArea {
            get {
                return this.ReceiveAreaField;
            }
            set {
                if ((object.ReferenceEquals(this.ReceiveAreaField, value) != true)) {
                    this.ReceiveAreaField = value;
                    this.RaisePropertyChanged("ReceiveArea");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ReceiveCity {
            get {
                return this.ReceiveCityField;
            }
            set {
                if ((object.ReferenceEquals(this.ReceiveCityField, value) != true)) {
                    this.ReceiveCityField = value;
                    this.RaisePropertyChanged("ReceiveCity");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ReceiveDepartment {
            get {
                return this.ReceiveDepartmentField;
            }
            set {
                if ((object.ReferenceEquals(this.ReceiveDepartmentField, value) != true)) {
                    this.ReceiveDepartmentField = value;
                    this.RaisePropertyChanged("ReceiveDepartment");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ReceiveName {
            get {
                return this.ReceiveNameField;
            }
            set {
                if ((object.ReferenceEquals(this.ReceiveNameField, value) != true)) {
                    this.ReceiveNameField = value;
                    this.RaisePropertyChanged("ReceiveName");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ReceivePhone {
            get {
                return this.ReceivePhoneField;
            }
            set {
                if ((object.ReferenceEquals(this.ReceivePhoneField, value) != true)) {
                    this.ReceivePhoneField = value;
                    this.RaisePropertyChanged("ReceivePhone");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ReceivePostCode {
            get {
                return this.ReceivePostCodeField;
            }
            set {
                if ((object.ReferenceEquals(this.ReceivePostCodeField, value) != true)) {
                    this.ReceivePostCodeField = value;
                    this.RaisePropertyChanged("ReceivePostCode");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ReceiveProvince {
            get {
                return this.ReceiveProvinceField;
            }
            set {
                if ((object.ReferenceEquals(this.ReceiveProvinceField, value) != true)) {
                    this.ReceiveProvinceField = value;
                    this.RaisePropertyChanged("ReceiveProvince");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ReceiveTelephone {
            get {
                return this.ReceiveTelephoneField;
            }
            set {
                if ((object.ReferenceEquals(this.ReceiveTelephoneField, value) != true)) {
                    this.ReceiveTelephoneField = value;
                    this.RaisePropertyChanged("ReceiveTelephone");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string SendAddress {
            get {
                return this.SendAddressField;
            }
            set {
                if ((object.ReferenceEquals(this.SendAddressField, value) != true)) {
                    this.SendAddressField = value;
                    this.RaisePropertyChanged("SendAddress");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string SendArea {
            get {
                return this.SendAreaField;
            }
            set {
                if ((object.ReferenceEquals(this.SendAreaField, value) != true)) {
                    this.SendAreaField = value;
                    this.RaisePropertyChanged("SendArea");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string SendCity {
            get {
                return this.SendCityField;
            }
            set {
                if ((object.ReferenceEquals(this.SendCityField, value) != true)) {
                    this.SendCityField = value;
                    this.RaisePropertyChanged("SendCity");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string SendDepartment {
            get {
                return this.SendDepartmentField;
            }
            set {
                if ((object.ReferenceEquals(this.SendDepartmentField, value) != true)) {
                    this.SendDepartmentField = value;
                    this.RaisePropertyChanged("SendDepartment");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string SendName {
            get {
                return this.SendNameField;
            }
            set {
                if ((object.ReferenceEquals(this.SendNameField, value) != true)) {
                    this.SendNameField = value;
                    this.RaisePropertyChanged("SendName");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string SendPhone {
            get {
                return this.SendPhoneField;
            }
            set {
                if ((object.ReferenceEquals(this.SendPhoneField, value) != true)) {
                    this.SendPhoneField = value;
                    this.RaisePropertyChanged("SendPhone");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string SendPostCode {
            get {
                return this.SendPostCodeField;
            }
            set {
                if ((object.ReferenceEquals(this.SendPostCodeField, value) != true)) {
                    this.SendPostCodeField = value;
                    this.RaisePropertyChanged("SendPostCode");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string SendProvince {
            get {
                return this.SendProvinceField;
            }
            set {
                if ((object.ReferenceEquals(this.SendProvinceField, value) != true)) {
                    this.SendProvinceField = value;
                    this.RaisePropertyChanged("SendProvince");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<int> SendSortCenterID {
            get {
                return this.SendSortCenterIDField;
            }
            set {
                if ((this.SendSortCenterIDField.Equals(value) != true)) {
                    this.SendSortCenterIDField = value;
                    this.RaisePropertyChanged("SendSortCenterID");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string SendTelephone {
            get {
                return this.SendTelephoneField;
            }
            set {
                if ((object.ReferenceEquals(this.SendTelephoneField, value) != true)) {
                    this.SendTelephoneField = value;
                    this.RaisePropertyChanged("SendTelephone");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<int> Status {
            get {
                return this.StatusField;
            }
            set {
                if ((this.StatusField.Equals(value) != true)) {
                    this.StatusField = value;
                    this.RaisePropertyChanged("Status");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<int> UpdateBy {
            get {
                return this.UpdateByField;
            }
            set {
                if ((this.UpdateByField.Equals(value) != true)) {
                    this.UpdateByField = value;
                    this.RaisePropertyChanged("UpdateBy");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<int> UpdateStationId {
            get {
                return this.UpdateStationIdField;
            }
            set {
                if ((this.UpdateStationIdField.Equals(value) != true)) {
                    this.UpdateStationIdField = value;
                    this.RaisePropertyChanged("UpdateStationId");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<System.DateTime> UpdateTime {
            get {
                return this.UpdateTimeField;
            }
            set {
                if ((this.UpdateTimeField.Equals(value) != true)) {
                    this.UpdateTimeField = value;
                    this.RaisePropertyChanged("UpdateTime");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public long WaybillNo {
            get {
                return this.WaybillNoField;
            }
            set {
                if ((this.WaybillNoField.Equals(value) != true)) {
                    this.WaybillNoField = value;
                    this.RaisePropertyChanged("WaybillNo");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="WaybillLifeCycleService.IWaybillLifeCycle")]
    public interface IWaybillLifeCycle {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IWaybillLifeCycle/HelloLifeCycle", ReplyAction="http://tempuri.org/IWaybillLifeCycle/HelloLifeCycleResponse")]
        string HelloLifeCycle(string yourName);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IWaybillLifeCycle/AddLifeCycle", ReplyAction="http://tempuri.org/IWaybillLifeCycle/AddLifeCycleResponse")]
        int AddLifeCycle(Vancl.TMS.BLL.WaybillLifeCycleService.WaybillLifeCycleDto dto);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IWaybillLifeCycle/AddLifeCycles", ReplyAction="http://tempuri.org/IWaybillLifeCycle/AddLifeCyclesResponse")]
        int AddLifeCycles(Vancl.TMS.BLL.WaybillLifeCycleService.WaybillLifeCycleDto[] dtos);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IWaybillLifeCycle/Inbound", ReplyAction="http://tempuri.org/IWaybillLifeCycle/InboundResponse")]
        int Inbound(Vancl.TMS.BLL.WaybillLifeCycleService.InBound model);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IWaybillLifeCycle/BackStation", ReplyAction="http://tempuri.org/IWaybillLifeCycle/BackStationResponse")]
        int BackStation(Vancl.TMS.BLL.WaybillLifeCycleService.BackStation model);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IWaybillLifeCycle/OutStation", ReplyAction="http://tempuri.org/IWaybillLifeCycle/OutStationResponse")]
        int OutStation(Vancl.TMS.BLL.WaybillLifeCycleService.WaybillDeal model);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IWaybillLifeCycle/PickUpIntoStation", ReplyAction="http://tempuri.org/IWaybillLifeCycle/PickUpIntoStationResponse")]
        int PickUpIntoStation(Vancl.TMS.BLL.WaybillLifeCycleService.PickUp model, Vancl.TMS.BLL.WaybillLifeCycleService.ExpressModel expressOrderModel);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IWaybillLifeCycle/PickUpOutStation", ReplyAction="http://tempuri.org/IWaybillLifeCycle/PickUpOutStationResponse")]
        int PickUpOutStation(Vancl.TMS.BLL.WaybillLifeCycleService.PickUp model, Vancl.TMS.BLL.WaybillLifeCycleService.ExpressModel expressOrderModel);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IWaybillLifeCycleChannel : Vancl.TMS.BLL.WaybillLifeCycleService.IWaybillLifeCycle, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class WaybillLifeCycleClient : System.ServiceModel.ClientBase<Vancl.TMS.BLL.WaybillLifeCycleService.IWaybillLifeCycle>, Vancl.TMS.BLL.WaybillLifeCycleService.IWaybillLifeCycle {
        
        public WaybillLifeCycleClient() {
        }
        
        public WaybillLifeCycleClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public WaybillLifeCycleClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public WaybillLifeCycleClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public WaybillLifeCycleClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public string HelloLifeCycle(string yourName) {
            return base.Channel.HelloLifeCycle(yourName);
        }
        
        public int AddLifeCycle(Vancl.TMS.BLL.WaybillLifeCycleService.WaybillLifeCycleDto dto) {
            return base.Channel.AddLifeCycle(dto);
        }
        
        public int AddLifeCycles(Vancl.TMS.BLL.WaybillLifeCycleService.WaybillLifeCycleDto[] dtos) {
            return base.Channel.AddLifeCycles(dtos);
        }
        
        public int Inbound(Vancl.TMS.BLL.WaybillLifeCycleService.InBound model) {
            return base.Channel.Inbound(model);
        }
        
        public int BackStation(Vancl.TMS.BLL.WaybillLifeCycleService.BackStation model) {
            return base.Channel.BackStation(model);
        }
        
        public int OutStation(Vancl.TMS.BLL.WaybillLifeCycleService.WaybillDeal model) {
            return base.Channel.OutStation(model);
        }
        
        public int PickUpIntoStation(Vancl.TMS.BLL.WaybillLifeCycleService.PickUp model, Vancl.TMS.BLL.WaybillLifeCycleService.ExpressModel expressOrderModel) {
            return base.Channel.PickUpIntoStation(model, expressOrderModel);
        }
        
        public int PickUpOutStation(Vancl.TMS.BLL.WaybillLifeCycleService.PickUp model, Vancl.TMS.BLL.WaybillLifeCycleService.ExpressModel expressOrderModel) {
            return base.Channel.PickUpOutStation(model, expressOrderModel);
        }
    }
}
