//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.269
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace ConsoleAppTest.TMSAPIService {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="TMSAPIService.ITMSAPIService")]
    public interface ITMSAPIService {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ITMSAPIService/DataEntrance", ReplyAction="http://tempuri.org/ITMSAPIService/DataEntranceResponse")]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(Vancl.TMS.Model.Sorting.Inbound.ViewInboundSimpleModel))]
        Vancl.TMS.Model.Common.ResultModel DataEntrance(Vancl.TMS.Model.Delivery.DataInteraction.Entrance.TMSEntranceModel entranceModel);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ITMSAPIService/SimpleInbound", ReplyAction="http://tempuri.org/ITMSAPIService/SimpleInboundResponse")]
        Vancl.TMS.Model.Sorting.Inbound.ViewInboundSimpleModel SimpleInbound(Vancl.TMS.Model.Sorting.Inbound.InboundSimpleArgModel argument);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ITMSAPIService/GetInboundCount", ReplyAction="http://tempuri.org/ITMSAPIService/GetInboundCountResponse")]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(Vancl.TMS.Model.Sorting.Inbound.InboundSimpleArgModel))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(Vancl.TMS.Model.Sorting.Inbound.InboundPreConditionModel))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(Vancl.TMS.Model.Sorting.Inbound.ViewInboundSimpleModel))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(Vancl.TMS.Model.Sorting.Common.SortCenterSimpleArgModel))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(Vancl.TMS.Model.Sorting.Common.SortCenterUserModel))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(Vancl.TMS.Model.Sorting.Common.SortCenterToStationModel))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(Vancl.TMS.Model.Delivery.DataInteraction.Entrance.TMSEntranceModel))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(Vancl.TMS.Model.Delivery.DataInteraction.Entrance.BillDetailModel[]))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(Vancl.TMS.Model.Delivery.DataInteraction.Entrance.BillDetailModel))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(Vancl.TMS.Model.Common.Enums.GoodsType))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(Vancl.TMS.Model.Common.Enums.BillType))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(Vancl.TMS.Model.Common.Enums.TMSEntranceSource))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(Vancl.TMS.Model.Common.ResultModel))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(Vancl.TMS.Model.Common.Enums.SortCenterFormType))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(Vancl.TMS.Model.Common.Enums.CompanyFlag))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(Vancl.TMS.Model.Common.Enums.BillStatus))]
        int GetInboundCount(object argument);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ITMSAPIService/GetUserModel", ReplyAction="http://tempuri.org/ITMSAPIService/GetUserModelResponse")]
        Vancl.TMS.Model.Sorting.Common.SortCenterUserModel GetUserModel(int UserID);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ITMSAPIService/GetToStationModel", ReplyAction="http://tempuri.org/ITMSAPIService/GetToStationModelResponse")]
        Vancl.TMS.Model.Sorting.Common.SortCenterToStationModel GetToStationModel(int ArrivalID);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ITMSAPIService/GetPreCondition", ReplyAction="http://tempuri.org/ITMSAPIService/GetPreConditionResponse")]
        Vancl.TMS.Model.Sorting.Inbound.InboundPreConditionModel GetPreCondition(string DistributionCode);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface ITMSAPIServiceChannel : ConsoleAppTest.TMSAPIService.ITMSAPIService, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class TMSAPIServiceClient : System.ServiceModel.ClientBase<ConsoleAppTest.TMSAPIService.ITMSAPIService>, ConsoleAppTest.TMSAPIService.ITMSAPIService {
        
        public TMSAPIServiceClient() {
        }
        
        public TMSAPIServiceClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public TMSAPIServiceClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public TMSAPIServiceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public TMSAPIServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public Vancl.TMS.Model.Common.ResultModel DataEntrance(Vancl.TMS.Model.Delivery.DataInteraction.Entrance.TMSEntranceModel entranceModel) {
            return base.Channel.DataEntrance(entranceModel);
        }
        
        public Vancl.TMS.Model.Sorting.Inbound.ViewInboundSimpleModel SimpleInbound(Vancl.TMS.Model.Sorting.Inbound.InboundSimpleArgModel argument) {
            return base.Channel.SimpleInbound(argument);
        }
        
        public int GetInboundCount(object argument) {
            return base.Channel.GetInboundCount(argument);
        }
        
        public Vancl.TMS.Model.Sorting.Common.SortCenterUserModel GetUserModel(int UserID) {
            return base.Channel.GetUserModel(UserID);
        }
        
        public Vancl.TMS.Model.Sorting.Common.SortCenterToStationModel GetToStationModel(int ArrivalID) {
            return base.Channel.GetToStationModel(ArrivalID);
        }
        
        public Vancl.TMS.Model.Sorting.Inbound.InboundPreConditionModel GetPreCondition(string DistributionCode) {
            return base.Channel.GetPreCondition(DistributionCode);
        }
    }
}
